jenkins.sh

Without this, the log file builds up forever, with details of every HTTP request Smokey has ever made. Since we'll be capturing log output for anything interesting anyway, this isn't useful to us.

Empty out the RestClient log after each run

---

deploy.sh

Using a non-interactive shell when executing `bundle` uses bundler which is installed as a system gem.
Newly provisioned machines do not have bundler installed as a system gem and need to use rbenv, which requires an interactive login shell to set up.

Use an interactive shell when deploying

---

features/performance_platform.feature

Tests have been frequently timing out, so increase the value for now, as discussed with @mattrco.

Make performance platform tests less brittle.

---

features/smartanswers.feature

As can be checked on preview by visiting `/student-finance-calculator/y/2013-2014/full-time`, the answer kept redirecting to the first question, because the dates in the URL are no longer valid as answers. Therefore the test was not testing the flow as intended.
This picks another answer to test against that is less likely to change the possible answers.

Update smartanswers test to step through a different answer

---

features/search.feature

Currently only one of the scenarios is run by nagios, this tags the others so that they are included.  It also removes one scenario that duplicates another one.

Update search feature

---

features/step_definitions/whitehall_steps.rb

The policies list is moving to `finder-frontend`, which has
slightly different class names. Update the selector to match
the policies as presented by `finder-frontend`
The movement of policies to `finder-frontend` has been done
on preview, but will happen on production when the new 
government is formed.
Until then this PR will actually introduce Smokey errors on
production. I'm not sure if we have have separate preview/
staging/production deploys for Smokey, if so this can be 
deployed to preview, but we'd want to hold off deploying
to prod until the government forms.
It might just be easier to leave this PR until that point, and
ack the preview errors. Thoughts from 2ndline, as they'll
be dealing with any alerts in the meantime?

[Do not merge yet] Update policy selector to fix broken step

---

features/whitehall.feature

The destination pages sometimes time out and cause false positives - what we care about here is that the URLs redirect.
Pinning these to the destination will probably also cause false positives if any of the slugs change.

Only test that department short URLs redirect

---

Rakefile
cron_json.sh
features/whitehall.feature

- We no longer use Nagios for monitoring
- Make the tag name more descriptive

Rename @notnagios Cucumber tag

---

features/support/base_urls.rb

These applications used to be used but the tests have been removed from Smokey.

Remove application URLs that are no longer used

---

features/gov_uk.feature

The 301 response that we send when we strip the trailing slash contains a relative location rather than the absolute URL.
Thanks/sorry @jennyd @dsingleton.

Change trailing slash test to use a relative path

---

features/signon.feature
features/step_definitions/cookie_steps.rb

These cookies need to be secure because they contain authentication
information. We set the HttpOnly flag because there's no reason for
client-side script to access the cookie.
My intention with the regular expression is to match the following:
- A delimiter in the Set-Cookie header (semicolon)
- Then a space
- Then the name of the property we want to find
- Then either another delimiter (semicolon) or the end of the header

Add signon cookie tests

---

Rakefile
features/contacts.feature
features/government_frontend.feature

This adds a rake task for running smokey features for the draft stacks: 
```
$ bundle exec rake test:preview_draft
```
and
```
$ bundle exec rake test:draft
```
Features that apply to the draft stack should be marked with the `@draft` tag.
It's worth noting that we do not currently have any features for either static or manuals-frontend.

Draft smokey features

---

features/contacts.feature

The two URLs being tested here are actually two different applications: the index is a finder, and the contacts themselves are served by contacts-frontend. This separates the two features so that they can be tagged separately as the finder is not actually running on the draft stack.

Separate contacts smokey features

---

features/contacts.feature

The check just looks through the page body to find the given text. Because the ampersand is encoded in the HTML, the string "Revenue & Customs" doesn't exist.

Fix ampersand in contacts feature

---

Rakefile
features/contacts.feature
features/draft_environment.feature
features/government_frontend.feature
features/step_definitions/draft_environment_steps.rb
features/step_definitions/signon_steps.rb

This adjusts the organisation of the smokey features such that there are
specific ones that are only run on the draft stack.
Ideally, there wouldn't be entirely separate scenarios for testing the draft
stack, but unfortunately the existing scenarios that call the "When I visit X"
step are not compatible with user sessions as under the hood they make the
requests using RestClient and not the capybara driver. Without rewriting all the
existing scenarios to use the proper driver, it would be too mucky to make these
scenarios work on both draft and non-draft stacks.

Update smokey to work with draft stack

---

features/transactions_explorer.feature

The url tested by this smoke test redirects to /performance/services.
The transactions explorer appears to no longer be running.

Remove transactions explorer smoke test

---

README.md
Rakefile
features/draft_environment.feature
features/step_definitions/draft_environment_steps.rb
features/step_definitions/smokey_steps.rb
features/support/capybara_mechanize_request_tracing.rb
features/support/draft.rb
features/support/env.rb

the draft steps had been set up in such a way that there was an assumption
that smokey would be invoked with `GOVUK_WEBSITE_ROOT` set to point to
the draft environment.
Given that we've moved away from having a full duplicate stack for the
draft environment, we will now only run smoke tests in one place.
This change allows steps tagged with `@draft` to be directed towards the
draft environment urls.
I also added an extra step to some of the draft scenarios to check that
the watermark shows on the page (which is triggered by the `draft` css
class on the document body).
https://trello.com/c/crylF01S/304-make-draft-smoke-tests-run-as-part-of-normal-run

Activate smokey checks for draft environment

---

features/draft_environment.feature

in order to have the smokey checks verified through nagios (and thus
trigger monitoring alerts), they need to be assigned priorities.

Assign priorities to draft environment checks

---

features/draft_environment.feature
features/step_definitions/draft_environment_steps.rb

These check that the specialist publisher format documents can be loaded
in the draft environment.
The URLs chosen are arbitrary ones which hopefully should be in
existence.

Add tests for specialist publisher formats on draft

---

Gemfile
Gemfile.lock
README.md
features/support/env.rb

smokey incorrectly guesses the draft url in production.

Special case for production draft url

---

features/step_definitions/licensing.rb

Use GOVUK_APP_DOMAIN because it's more portable than hardcoding a hostname.

Fix licensify hostname

---

features/assets.feature
features/support/base_urls.rb

We don't have any end-to-end monitoring that checks whether the internal hostname for assets is functioning as we expect.
The canary is the only route I can think of which will remain stable on the assets hostname.

Add assets test

---

features/browse.feature
features/step_definitions/smokey_steps.rb
features/topics.feature

Add additional step to traverse browse categories across both first and
second levels, to improve monitoring of /browse path.
Stories: https://trello.com/c/VqFDnMot and https://trello.com/c/Dj4P9D8N

Update smokey to check browse and topics dynamically

---

features/gov_uk.feature
features/step_definitions/smokey_steps.rb
features/step_definitions/travel_advice_steps.rb
features/support/env.rb
features/travel_advice.feature

We had an incident recently where we accidentally changed the content of travel advice feeds which caused GovDelivery to send email alerts when there were no actual updates.
This commit tests that the GOVUK_WEBSITE_ROOT environment variable is configured correctly on our machines. In preview and staging the expected value is always equal to the actual value. This test is only valuable in production where it makes sure that the website root is set to `https://www.gov.uk`.
I've also had to add a new step definition to include the value of the environment variable which I'm not particularly happy about but it's the best I've come up with so far.
---
I'm not particularly happy with any of this code which is probably an indication that it's the wrong approach to be taking. If anyone has any …

[#104329818] Add monitoring for GOVUK_WEBSITE_ROOT

---

features/step_definitions/smokey_steps.rb

Smokey currently outputs the current page when traversing browse and topic pages. This makes the log output a bit noisy in CI.
@mobaig agree?

Remove logging for /browse & /topic test

---

features/support/mechanize.rb

There are 2 ways of making http requests in smokey. One using
rest-client directly, and one using capybara with the mechanize driver.
The RATE_LIMIT_TOKEN had only been implemented for the rest-client
methods.
This adds the same for capyabra with mechanize.

Make mechanize use the RATE_LIMIT_TOKEN if set.

---

features/step_definitions/whitehall_steps.rb

In staging, rummager is often out of sync with the whitehall DB, and so
the top announcement may not exist in Whitehall itself, resulting in a
404. Using the top announcement from page 2 is a lot more likely to
succeed.

Check an announcement from page 2 of the list

---

README.md
Rakefile
features/efg.feature
features/support/base_urls.rb
features/support/env.rb
features/whitehall.feature
manual_test/smokey.json

The preview environment has been retired and replaced by the
integration environment in Dec 2015.
/cc @jamiecobbett

Replace 'preview' references with 'integration'

---

features/frontend.feature
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

This change involves adding another config option to the test helpers to prevent an exception being raised.
This adds coverage for https://github.com/alphagov/govuk-puppet/pull/3816 .
/cc @alexmuller @mattbostock

Frontend tests: checks for content type

---

features/frontend.feature

[Frontend PR #907](https://github.com/alphagov/frontend/pull/907) changed the wording on the location lookup form which broke Smokey tests.  This is an interim fix. A more robust resolution will be submitted next week.
[Trello card for follow up work](https://trello.com/c/l7ViHu5u/247-fix-frontend-smokey-tests)

Fix Smokey error due to Frontend UI changes

---

features/frontend.feature
features/step_definitions/frontend_steps.rb

For https://trello.com/c/l7ViHu5u/247-improve-frontend-smokey-tests-1-day
This is an attempt to make tests for entering a postcode less brittle by moving away from searching for the string of the label "Enter a postcode" and towards searching for the input field by class. That enables us to change the label text in the frontend app without breaking the smokey tests.
See discussion in https://github.com/alphagov/smokey/pull/169

Update postcode form step to check for input element

---

features/licensing.feature

Smokey tests started to fail for licensify-admin for reasons not quite yet determined. Upon testing manually, the assigned user is able to login but is not presented with any applications. This appears to be
correct behaviour, but the search term that is specified is not present. This commit updates it to a specific term when that user logs in.
/cc @alexmuller who added the test in f5e48da4 to ensure that what we're seeing _is_ the correct behaviour.

Update licensify-admin Smokey search term

---

features/licencefinder.feature

Someone added a test license so the search term changed again. Changed the search term to "Sign Out" which is present if one is logged in, but _shouldn't_ change if test licenses are added (and/or if there is a difference between Staging and Production).

Change search term for Smokey licensing test

---

features/step_definitions/email_campaign_steps.rb

This reverts 7140dc737d9a243bf289e9683800f842d1491af8 which was done in relation to a Capybara 2 upgrade which has now also been reverted.

Revert email campaign click_link

---

nagios_check_cache.py

syslog chokes with non-ASCII characters (returning a very unhelpful
"TypeError: [priority,] message string"). But on a failing test, we log
the entire page output, which includes the (non-ASCII) copyright symbol.
Encode messages to ASCII with the 'xmlcharrefreplace' codec, which
replaces the values with their XML-escaped equivalents.

Fix logging of errors.

---

features/mirror.feature

The page at `/council-tax-reduction` is now a redirect.

Update page that's tested on the mirrors

---

features/mainstream_publishing_tools.feature

Travel advice is one of the critical parts of GOV.UK and we should be treating tests for it at least as urgently as those for other publishing applications.
This will make this scenario be run as part of the [`Run mainstream_publishing_tools high priority tests` Icinga check](https://alert.publishing.service.gov.uk/cgi-bin/icinga/extinfo.cgi?type=2&host=monitoring-1.management.publishing.service.gov.uk&service=Run+mainstream_publishing_tools+high+priority+tests) - it isn't being run from Icinga at the moment, only from Jenkins after deploys.
Should this scenario actually be `@urgent` given the importance of travel advice? Would that make us more likely to notice quickly if it's broken?

Make travel advice publisher scenario high priority

---

features/mainstream_publishing_tools.feature

This app exists to maintain a dataset which will soon be used to power a
mainstream format, so I've put it in the `mainstream_publishing_tools` feature.

Add a scenario to test logging into local links manager

---

features/performance_platform.feature

'Given I am testing through the full stack' sets the `@host` variable
to the GOVUK_WEBSITE_ROOT environment variable

Ensure @host is present when calling the performance feature

---

Gemfile
Gemfile.lock

This removes these deprecation warnings:
```
[DEPRECATION] "eval" is deprecated. Please use "evaluate" instead
```
https://github.com/cucumber/cucumber-ruby/blob/master/History.md#125

Upgrade cucumber to 1.2.5

---

features/gov_uk.feature

Functionality has been added to the router LB that downcases URLs that are entirely in capitals. This PR adds checks that:
* Entirely upper case urls are 301 redirected to their lowercase equivalent
* Partially upper case urls are ignored
Part of [Trello](https://trello.com/c/CDpTRF1e/408-404s-caused-by-capitalisation-medium)

Add downcase feature

---

features/gov_uk.feature
features/step_definitions/smokey_steps.rb

The recent features added to test the 'downcase all caps urls' functionality added in https://github.com/alphagov/govuk-puppet/pull/4573 were broken. This commit updates adds some steps to ensure the correct host is added and that the location is correctly checked.

Fix gov_uk.feature

---

features/frontend.feature

This test uses a specific name for London Borough of Camden / Camden Borough
Council to verify the test.  We get council names from a variety of sources
and we want to somewhat insulate the test from the fact that these names change
from time to time.  
We are in the middle of switching from Publisher to Local Links Manager as the data source for Local Transaction links, and the data in each is slightly different due to the original sources disagreeing.

Make Local Transaction test less brittle

---

features/mirror.feature
features/step_definitions/mirror_steps.rb

Why?
From 2ea193e in static, we contract "we are" to "we're" on the 503
page.
How?
- Update the error string we check for in the mirror scenarios.
- Refactor into a single step definition, rather than repeating the
string multiple times in the feature file.

Update error message assertion in mirror feature

---

features/content_api.feature

/api/tags.json is scheduled for retirement. This changes the smokey test to test for a different endpoint instead. /vehicle-tax seems a stable page since it's linked from the homepage.
https://trello.com/c/jvuqHiS7

Visit a different endpoint for content-api

---

features/step_definitions/smokey_steps.rb

It has changed from using a GET request to a POST request
We're not sure if this is supposed to be the case and this may need reverting if/when Trade Tariff is changed back to using GET.

Fix the Trade Tariff search

---

features/licensing.feature

These tests fail on integration.
Quote @timblair:
> So that's trying to download the relevant PDF form from Apto (the 3rd party that manages the PDFs for us), and it's failing, probably because the database in integration doesn't have the correct details in it.
It's on Tim's todo list now. In the meantime, this commit disables the test temporarily.

Disable licensing tests on integration

---

features/design_principles.feature

This text has been changed to "Start with user needs".
This updates smokey after [this change to the text in the Design Principles app](https://github.com/alphagov/design-principles/pull/273).

Update smokey test for "Start with needs"

---

features/step_definitions/smokey_steps.rb

The URL requires basic auth which needs to be added manually since the
request doesn't go via the `get_request` method.

Fix tariff search feature.

---

features/finder_frontend.feature
features/step_definitions/finder_frontend_steps.rb

Trello: https://trello.com/c/4J5oJ6CU/275-migrate-whitehall-index-pages-to-finders
Finding Things team has migrated some index pages to finders, this
commit makes sure those pages are tested through smokey.
- People finder
- World Organisations finder
- Groups finder
This commit depends on two PR's to be merged on Whitehall repository:
- https://github.com/alphagov/whitehall/pull/2831
- https://github.com/alphagov/whitehall/pull/2832

Add migrated finders to be tested

---

features/finder_frontend.feature

Finding Things team has migrated these pages to a finder. This commit
makes sure it gets tested trough smokey test suite.
Trello: https://trello.com/c/4J5oJ6CU/275-epic-migrate-whitehall-index-pages-to-finders

Add new finders into smokey test suite

---

features/frontend.feature
features/step_definitions/smokey_steps.rb

Frontend now uses a GET request when the user searches for a postcode (not a POST request anymore). This commit makes the smokey tests pass again.

Fix place postcode request test

---

features/frontend.feature

This was previously making a JSON request and testing some little used functionality in Frontend, which we did not test for in the app itself. We checked in Kibana and apart from Smokey no-one else appears to be posting to JSON place routes. We've chosen to remove this functionality as it simplifies the code in Frontend and do not want to be supporting legacy APIs just for the sake of it.

Update find my nearest test to make html request

---

tests_json_output.sh

Including the quotes meant that cucumber received an argument of the empty
string, which caused it to crash. I don't quite understand why, but just
removing the quotes means that no argument is included, and cucumber executes
successfully.

Remove quotes from the PROFILE parameter expansion

---

features/efg.feature

Smokey has been failing regularly on this test. We've never noticed before, but now we do since we've started posting the smokey failures in slack.
This bumps the threshold for "slow" requests to EFG to 10 seconds. I think we should possibly get rid of all benchmarking in smokey, but this is a start.
Example:
https://deploy.publishing.service.gov.uk/job/Smokey/4157/console

Allow EFG to be slower

---

features/design_principles.feature
features/service_manual.feature

`design-principles` is no longer involved in serving the service manual – it’s entirely served by `service-manual-frontend`. Move the service manual homepage test from the design principles feature to the service manual feature.
Additionally, the search for the service manual is now handled by the global `/search` in combination with `filter_manual` so this does not need to be tested separately.

Update Smokey tests for Design Principles

---

features/private_frontend.feature
features/step_definitions/smokey_steps.rb
features/support/visiting_pages.rb
features/whitehall.feature

Our `visit_path` step sets up basic auth by default now, which means we get false positives for visiting authenticated pages.
This removes the misleading step and makes sure we test correctly.
https://trello.com/c/WIunrfiT

Fix intermittent test failures with auth

---

features/ab_testing.feature
features/step_definitions/ab_testing_steps.rb
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

Add feature tests for a help page which will display the state of an example A/B test (and potentially all A/B tests operating on gov.uk).
This test relies on A/B testing cookies being handled correctly by the server. This requires some CDN Varnish config (alphagov/govuk-cdn-config#13) which will only work on Production (and possibly Staging).
Since this doesn't work in dev, and since the real page doesn't exist yet, I've developed the tests against some temporary changes to collections (see the [ab-smokey-dev branch](https://github.com/alphagov/collections/tree/ab-smokey-dev)).
Both feature tests make multiple requests for statistical sampling. I've set them to make 20 requests each, which takes about 10 seconds per test. I think 20 requests should be high enough - it gives us  10^6 …

Smoke test for A/B testing

---

tests_json_output.sh

The `@pending` tag is specified in the yaml configuration and also in
the command-line options that are passed from tests_json_output.sh. It
seems that specifying a tag twice causes Cucumber to skip all tests.
Removing the duplicate fixes the problem.

Remove duplicate tag in runner script.

---

config/cucumber.yml
features/ab_testing.feature
features/step_definitions/ab_testing_steps.rb
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

This is a repeat of #222, which was reverted because it didn't handle the capybara-webkit changes that been applied to master. Those have now been reverted themselves, so these feature tests can be run as-is.
I've also added a `@notstaging` annotation so that the tests are only run against production.
Trello: https://trello.com/c/0CbiIWOs/248-as-the-nav-team-we-want-to-enable-a-b-testing-across-gov-uk-applications-to-be-able-to-rollout-the-navigation-beta

Add feature tests for A/B test example page

---

Rakefile

This will allow us to run a specific task for our Staging environment, so any tests with a `@notstaging` should not run.

Add staging task

---

features/step_definitions/ab_testing_steps.rb

This test checks that we are correctly sending a page view tracking event to Google Analytics when A/B testing.
Note that this card is dependent upon:
Follow-up from: https://github.com/alphagov/smokey/pull/231 (the branch it was based on was deleted)
Trello: https://trello.com/c/g9OyC7Pn/310-tell-google-analytics-about-a-b-tests

Add test for Google Analytics AB tracking

---

Rakefile
features/bouncer.feature
features/businesssupportfinder.feature
features/licencefinder.feature
features/licensing.feature
features/whitehall.feature

The bechmarking tests often fail on jenkins because they're a bit flaky. In https://github.com/alphagov/smokey/pull/241 it was proposed to remove them altogether.
Because there's no other way of getting alerted for consistently poor performing pages, we agreed that the monitoring process (which runs smokey in a loop) will keep benchmarking. Jenkins will skip the tests, so that the after-deploy smoke tests don't fail as much.
@boffbowsh

Don't run benchmarking tests after deploy

---

features/ab_testing.feature
features/support/env.rb

This commit disables calls to GA from all smokey tests apart from the
A/B test where we need to make sure we submit events to GA.
Trello: https://trello.com/c/7ArY5dG6/421-don-t-load-google-analytics-in-smoke-tests

Disable GA in smokey apart from A/B tests

---

features/step_definitions/mirror_steps.rb
features/support/http_requests.rb

SSL certificates for the mirrors are offloaded to Fastly. The change from rest-client 1.6.7 to 1.8.0 changed the default from bypassing SSL certificate verification to peer validation.

Bypass SSL certificate verification for mirror requests

---

features/step_definitions/ab_testing_steps.rb
features/step_definitions/collections_steps.rb

This fixes a failing Smokey test for collections, which was not correctly setting up an A/B test

Fix collections test

---

features/collections.feature
features/step_definitions/ab_testing_steps.rb
features/step_definitions/collections_steps.rb

Regardless of a user having a cookie or not, when they go to the new
education pages in collections, they should be assigned to the B
variant.
These tests will verify that the VCL configuration is working as
expected.
This depends on https://github.com/alphagov/govuk-cdn-config/pull/35
being live.

Test that we place users in B variant on new nav

---

features/travel_advice.feature

The title of the root page has changed to Summary instead of
Current Travel Advice.

Update the Travel Advice root page title

---

features/private_frontend.feature
features/support/base_urls.rb

Private-frontend is being turned off, so we remove private-frontend tests from `smokey`.
[Trello](https://trello.com/c/JYT9roQm/709-turn-off-private-frontend)

Remove private-frontend tests

---

features/mainstream_publishing_tools.feature
features/support/base_urls.rb

This follows the pattern of the other publishing tests.
One of the motivations for adding a Smoke test was to catch the sort of timeout
problem we saw recently where the /manuals index page was taking too
long to load. Unfortunately, I don't think this test would've caught
that problem because the test signon user doesn't have any manuals to
load! Irrespective, I still think it's useful to have this sort of test
to ensure we get an early warning if we've really broken something.
The test signon user has the manuals-publisher permission. You can run
this test locally by using the signon credentials stored in the Smokey
job configuration in the integration Jenkins instance.
I've set the scenario as `@high` priority which means (if I understand [the
README][1] correctly) that it'll generate …

Add Cucumber scenario for manuals-publisher

---

features/mainstream_publishing_tools.feature

- Since we changed the style of the homepage to be broken links
instead of a list of LAs, this has been failing. Interestingly,
I think this has only been failing in Integration, yet in the
version of LLM we have in Production I can only see lowercase
"local authorities" which does not fit with what the test is
asking for (capitalised). Hmm.

Fix Local Links Manager failures

---

features/mainstream_publishing_tools.feature

It's not matching `Councils`, but should match `Council` unless all the data
disappears.

Be less specific about the matching text

---

features/ab_testing.feature
features/support/env.rb

This has the exception of 1 test case where we need to send an analytics
event, but it should disable Google Analytics across all other tests.
I've also added a User-Agent to poltergeist so that we can recognise
those requests, should we need to.
Finally, we will raise an error if the Google Analytics host is somehow
in the list of hosts from the driver's network traffic list. We don't
want for this to happen and there is a cucumber tag to enable it, in
case someone needs it (e.g. used for one A/B test).
This should fix issue #256
cc/ @tijmenb and @fofr

Disable analytics before each scenario

---

features/draft_environment.feature

`contacts-frontend` has been replaced with `government-frontend` and is now being retired. This PR removes tests specific to `contacts-frontend`.

Remove draft test for contacts-frontend

---

features/ab_testing.feature
features/step_definitions/ab_testing_steps.rb

We have a bunch of overrides for related links on the new
Education Navigation A/B test in place across different apps. This is
hard to test in the apps as we mock requests/responses, and we've seen
it breaking when we moved the rendering app of some of those pages.
This test should be deleted once we have a solution for related links in
the new navigation.
Trello: https://trello.com/c/U6JKZN6s/115-make-sure-we-override-the-related-links-on-some-mainstream-content-that-was-recently-moved-to-government-frontend
cc/ @fofr

Add test for related link overrides for A/B test

---

features/draft_environment.feature

* specialist documents are served by government-frontend
* manuals are served by manuals-fronted
The tests themselves don’t need to change.
Part of: https://trello.com/c/UM7aecOQ/194-final-stage-decomission-specialist-frontend-2

Re-phrase draft tests for specialist-frontend

---

features/asset_manager.feature

The assertion on that url is no longer "static" so I changed it to fix the test.

corrected an assertion for asset manager

---

features/content_api.feature
features/support/base_urls.rb

We no longer support the Content API and officially there is no other
app using it.
Trello: https://trello.com/c/Uo9tfmSE/139-investigate-who-is-using-travel-advice-endpoints-on-content-api-in-production

Remove Content API tests

---

features/smartanswers.feature

Due to the @normal priority, this is one of the things that the
nagios_check_cache.py script checks, except, when this was changed to
an outline, the results don't appear to be included. This means that
the script breaks.
To fix this, change it back to an scenario. There is another example
of a scenario outline, but because it lacks a priority, it doesn't
break the script.

Rewrite scenario outline as scenario

---

features/publicapi.feature
features/step_definitions/calendar_steps.rb
features/step_definitions/smokey_steps.rb

This commit adds some tests to ensure the public API is available and returning JSON. It tests the search API, content API and the various whitehall APIs. It does not test whether the data returned by the APIs is correct.
It also moves the step definition for testing for JSON responses to a more generic file since it is now used in mutiple tests.

Add tests for the public API

---

features/publicapi.feature

The content API no longer exists and the test is actually testing the content store.

Rename content API to content store

---

features/ab_testing.feature

We can run this test in all environments because it sets HTTP headers
besides setting the cookies, which means the A/B test works.
This will make sure we catch issues early on regarding the overrides on
related links.
This was related to an issue when migrating pages from smart-answers.
Relevant links:
- https://github.com/alphagov/frontend/pull/1261
- https://github.com/alphagov/smart-answers/pull/3134
Tested on:
- Integration: https://deploy.integration.publishing.service.gov.uk/job/Smokey/18193/console
- Staging: https://deploy.staging.publishing.service.gov.uk/job/Smokey/6367/console

Run A/B tests for sidebar overrides in all envs

---

features/ab_testing.feature
features/step_definitions/ab_testing_steps.rb

This reverts commit 87875255da41bc5b7eccd2a441dc01cba000e331.
Trello: https://trello.com/c/WrLDSJYm/26-deploy-new-curated-related-links-for-student-loans-content
Related PRs:

Revert "Add test for related link overrides for A/B test"

---

features/draft_environment.feature
features/government_frontend.feature

As the epic-cic page contains JavaScript from YouTube which errors
when tested through Smokey. The libraries-unlimited page is a case
study which does not have this JavaScript present.

Switch epic-cic to libraries-unlimited

---

features/support/env.rb

This is a precursor to PR #280.
I want to add 'www.youtube.com' to the URL blacklist but doing so made it apparent that the current implementation was quite closely tied to blacklisting 'www.google-analytics.com'. I think/hope this change makes the intention of the URL blacklisting a bit clearer.
This builds upon both PR #245 and PR #260.

Simplify URL blacklisting configuration

---

features/support/env.rb

This fixes the intermittent error we've been seeing in the "check
Transformation dashboard" scenario of the "Design Principles" feature;
as reported in issue #279.
I ran the problematic scenario 10 times before this fix and 10 times
after:
$ bundle exec cucumber features/design_principles.feature:14
I saw 6 failures and 4 successes before the fix and 10 successes
afterwards so I'm fairly confident this will solve the intermittent
failures we've been seeing.
Blacklisting youtube.com doesn't appear to negatively affect any of the
other scenarios.

Add youtube.com to Poltergeist's blacklist of URLs

---

features/draft_environment.feature
features/government_frontend.feature

Reverts alphagov/smokey#277
We can switch back to using a case study that includes a video thanks to #280.

Revert "Switch epic-cic to libraries-unlimited"

---

features/step_definitions/ab_testing_steps.rb

This test was failing because the regexp didn't match the URL of the
request that's actually made to Google Analytics.
This failure only became apparent after merging PR #281. Prior to
merging this PR, this test wasn't running at all: It was failing in the
`Around('@withanalytics')` block when trying to set
`page.driver.browser.url_blacklist = []` as `page` is nil.
You can observe the problem by checking out the commit prior to PR #281
(`git checkout f069ccdf167483a34025a9313a7e42b48fe0ed76~`) and running
the test:
$ GOVUK_WEBSITE_ROOT=https://www.gov.uk \
bundle exec cucumber \
--format pretty features/ab_testing.feature:19
@withanalytics @low @notintegration @notstaging
Scenario: check that an A/B test works # features/ab_testing.feature:19
undefined local variable or method `page' for …

Fix broken A/B test

---

features/smartanswers.feature
features/step_definitions/smartanswers_steps.rb

Following an incident where the country pickers were showing no (or very
few) countries on Smart Answers, this change adds tests to check that
the dropdowns are populated with a sensible-looking number of elements.
This test is needed, because Smart Answers relies on getting countries
from Whitehall, so we should test this integration.
The tests check for the number of countries being greater than 200,
which should provide a sense check without requiring constant updating
of the list of countries every time Whitehall or Smart Answers changes.

Add test for Smart Answers country pickers

---

features/smartanswers.feature
features/step_definitions/smartanswers_steps.rb

Smart Answers relies on the Worldwide API for:
- Country dropdowns (tested in a [separate change](https://github.com/alphagov/smokey/pull/286))
- Display of country names
- Validation of country slugs
- FCO details
This change adds integration tests for the above, to test that Smart Answers is using the Worldwide API as expected.

Add Smart Answers Worldwide API Tests

---

features/smartanswers.feature

Smart Answers relies on the Imminence API for postcode lookup. This
change adds tests that exercise this API call.

Add Smart Answers test for using the Imminence API

---

features/smartanswers.feature

The Benefit Cap Calculator in Smart Answers was recently updated, which
changed the path to reach a postcode check.
This change updates the path we’re checking to use this new format.

Update Benefit Cap Calculator path

---

tests_json_output.sh

In a recent Pull Request, we introduced the use of Cucumber’s
[`Scenario Outline`](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines).
This change caused us failures in our monitoring, because the monitoring
expects all `step` items in the JSON to have an associated `result` key.
This is not the case in the default JSON formatting, as can be seen
[here](https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline).
What we actually want is to expand the JSON formatting, so that each
of the `Scenario Outline` steps has a `result`, like [this](https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline-expanded).
This change enables the `--expand` flag, which will report the results
for each step as demonstrated …

Expand JSON output to include Scenario Outline results

---

features/finder_frontend.feature
features/step_definitions/finder_frontend_steps.rb

This tests for issues like this:
https://docs.publishing.service.gov.uk/manual/incorrect-content-in-search-or-navigation.html#there-are-blank-options-on-finder-pages
The root cause in this case is rummager holding inconsistent data.  It knows
pages are tagged to people/organisations/topics but sometimes it's missing the
thing being tagged to.
In this case finder frontend just renders the thing with a blank title.
We could handle this better in finder frontend, but I think if the labels are ever
blank it should fail smokey, as this means the finder is not working properly.
Trello: https://trello.com/c/oTkICgvO/291-stop-blank-people-appearing-in-policy-finder

Check what facets look like in finder pages

---

features/search.feature
features/step_definitions/search_steps.rb

This only checks a couple of common search terms, but should catch some obvious bugs
affecting high volume content.
Note: This test currently fails due to a bug with search we are fixing. https://trello.com/c/jx2JMs9R/301-prevent-duplicate-search-results-for-smart-answers

Check that search results are not duplicated

---

features/finder_frontend.feature

I wrote the test assuming the user agent is assigned to the A bucket.
Trello: https://trello.com/c/oTkICgvO/291-stop-blank-people-appearing-in-policy-finder

Make finder tests aware of the policy finder A/B test

---

features/finder_frontend.feature

Trello: https://trello.com/c/IaqLA1eG
The titles of the policies finders were reverted to their originals
in PR https://github.com/alphagov/policy-publisher/pull/169

Change the titles for the policies finders

---

features/design_principles.feature

It is now redirected rather than rendered by the application.

Update design principles to reflect redirect

---

features/csv.feature
features/step_definitions/csv_steps.rb

This commit adds a test for the whitehall CSV preview to ensure JavaScript is running without any errors on those pages.
Trello: https://trello.com/c/BoQt5GLG/195-add-smokey-test-for-csv-preview-incident-review-action

Add test for CSV preview

---

config/cucumber.yml
features/mirror.feature

- We don't have a VPN set up from AWS to the mirror boxes, so these
Smokey tests are failing. Avoid this noise in our AWS environment by
disabling these tests in that case.

Don't run mirrorer tests on AWS

---

features/step_definitions/collections_steps.rb

A new accordion component has been released in Collections.  This has different
classes to the previous version, so we need to update the smoke test.
Paired with @andysellick

Update for accordion component

---

features/design_principles.feature

The transformation dashboard has been retired. Updates the test to reflect that we now redirect to a government publication.
See https://govuk.zendesk.com/agent/tickets/2461119

Update test for transformation dashboard

---

features/performance_platform.feature

Spotlight should no longer be running in integration or staging, and so
only production tests are useful.

Only test performance platform in production

---

features/search.feature
features/step_definitions/search_steps.rb

Previously some of our search tests had a "the search results should have
different titles" step which intends to check that no duplicate results are
displayed in search.  However, it is possible for two different pieces of
content to have the same title, so this step is a bit flaky.  To resolve this
issue we replace this step with "the search results should be unique", which
checks the combined search result title and description for uniqueness to
determine whether duplicate search results are appearing.

Add search step to check for unique results

---

features/support/env.rb

This adds a bunch of domains that I am hoping will be future proofing against smokey tests in the future. For now, it's only https://www-origin.blue.integration.govuk.digital that really affects us, but I didn't see any harm in adding the others.
Adds them into an array and uses a splat to iterate over them.

Add AWS domains to environment helper

---

features/mirror.feature

This PR removes two features that are currently failing due to a know SSL issue on the mirrors. This is being worked on but in the meantime we want Smokey to be in a green state for the rest of the tests and to be alerted appropriately for failures in the rest of the suite.
This will be reverted once the other issue is fixed.
[Trello to revert](https://trello.com/c/nvWkhcLU/393-revert-smokey-mirror-test-removal)

Remove some mirror features

---

README.md
features/support/http_requests.rb

For the migration to AWS, we need to test the service domain works correctly before we do the switchover. To achieve this, we want to use Smokey as an indicator that stuff works like we expect.
Add an environment variable called `CUSTOM_DESTINATION_URI` that allows setting a custom domain. For our use, it will be something using the top level "integration.govuk.digital" domain, while setting the `GOVUK_WEBSITE_ROOT` and `EXPECTED_GOVUK_WEBSITE_ROOT` to the `integration.publishing.service.gov.uk`.
The code will update the destination, while ensuring the Host header is set as appropriate.

Allow setting of CUSTOM_DESTINATION_URI

---

features/assets.feature

This tests for the `Content-Type` header returned by asset-manager. We
have bugs in production where these files are returned without a
`Content-Type` header, causing Internet Explorer to display the file as
plain text.
The first of these files (the .docx) has had a manual fix applied where
the Content-Type header has been set explicitly on the key in S3. The
second (the .xls) relies on nginx passing through the header from
Rails. The theory is that the bug should not happen on the first file.
The bug normally takes around a day to occur due to the day-long
`max-age` returned.

Add test for assets content type

---

features/support/base_urls.rb

On AWS some of the end points are internal facing only and are
configured with an internal domain, for instance, Bouncer. Smokey
tests for these endpoints are failing because the monitoring box
is trying to use the public domain specified in GOVUK_APP_DOMAIN.
In this change we add a new environment variable, GOVUK_APP_DOMAIN_INTERNAL,
that, if configured, will be used to create some of the service URLs.
In this case we applied the internal domain to Bouncer.

Add support for bouncer APP_DOMAIN_INTERNAL

---

features/search.feature

We want to make sure that the returned search results are unique and have previously done this by using the title of a document. In practice our content does not always have unique titles so swap this to use links instead.

Check for unique link in search results feature

---

features/licencefinder.feature

These tests often fail on integration, causing us to get used to smokey errors.
It's better to skip intermittently failing benchmark scripts so that we'll have more confidence that when something actually fails we need to do something.

Don't run licence finder benchmarks on integration

---

features/government_frontend.feature
features/step_definitions/government_frontend_steps.rb

Tests the new service sign-in radio routing behaviour.
Uses a wait_until method since GOV.UK Verify does some odd double redirect behaviours.
As part of https://trello.com/c/9bkRCWy4/253-update-smokey-test

Add feature tests for service sign-in pages

---

jenkins.sh
tests_json_output.sh

Set to use Smokey environment variables like other applications rather than sourcing an independent file created by Puppet. This allows us to manage Smokey in a more consistent and less confusing way.

Set `govuk_setenv` to "smokey" env

---

features/step_definitions/government_frontend_steps.rb

When we run the Smokey tests, we get this warning:
> DEPRECATED: #default_wait_time is deprecated, please use #default_max_wait_time instead
(See https://deploy.publishing.service.gov.uk/job/Smokey/6745/console) 
This was deprecated in [Capybara v2.5.0][capybara] so we should probably resolve the warning.
[capybara]: https://github.com/teamcapybara/capybara/blob/57e3c9d92fc0f86879c2a7290a1d339f6ec86d70/History.md#deprecated

Fix capybara deprecation warning

---

features/support/base_urls.rb

On AWS we are seeing the error:
```
Failed to open TCP connection to asset-manager.integration.publishing.service.gov.uk:443 (getaddrinfo: Name or service not known) (SocketError)
```
asset-manager doesn't have a public domain, so we need to connect
internally.

User asset-manager with internal domain

---

features/step_definitions/search_steps.rb

This is required due to a change in how we are hidding these elements
and not a change in their visibility state.

Allow organisation selector to see hidden elements

---

features/assets.feature

These tests started failing when we merged https://github.com/alphagov/asset-manager/pull/418 to set the correct content-type for a number of additional file types.
These tests were added in 3725f865d22340698fad39ae7f3cca20d0d2ecfa as part of our investigation into the missing content-type issue captured in https://github.com/alphagov/asset-manager/issues/238. The cause of this problem was fixed in https://github.com/alphagov/asset-manager/pull/343 but we're keeping these tests around to help catch regression in future.

Fix failing tests for asset content-types

---

features/services_information.feature
features/step_definitions/smokey_steps.rb

We recently had an outage on Services and Information pages (like https://www.gov.uk/government/organisations/hm-revenue-customs/services-information). This adds a test that would have picked up the issue.
cc @suzannehamilton

Add test for Services and Information pages

---

features/finder_frontend.feature

This removes a test for a feature removed in https://github.com/alphagov/policy-publisher/pull/221. Also removes a duplicate of the "check policy page loads" test at L16.
We're no longer testing that the dropdown for "empty values", but as far as I know there aren't any finders with document type, person or policy dropdowns.
https://trello.com/c/YDda1PqI

Remove testing for policy firehose

---

Gemfile
Gemfile.lock
features/asset_manager.feature
features/licensing.feature
features/step_definitions/signon_steps.rb
features/step_definitions/smokey_steps.rb
features/support/base_urls.rb

Previously a rather awkward list of URLs was used. This replaces that
list with using Plek, and a hash of default paths. I don't think all
default paths are used, but just include all of the ones specified
previously for now.
This uses the new external_url_for method in Plek 2.1.0 to find
external URLs for services. Some changes to the step definitions are
made here to explicitly use external URLs in some circumstances.

Change the handling of base URLs

---

features/whitehall.feature

This test is confusing, as it seems to suggest it's testing through
the full stack, including varnish, but then attempts to access
whitehall-frontend directly.
This doesn't work on the new AWS Integration, so lets change this to
just visit the URL via the normal route.

Don't directly access Whitehall Frontend

---

features/asset_manager.feature
features/assets.feature

Previously this was hardcoded in the base_urls file, but now Plek is
used instead, so use the actual hostname that is required, rather than
assets.

Switch assets to assets-origin

---

features/step_definitions/licensing.rb

The application_external_url function puts a / on the end of the URL,
which resulted in two forward slashes, this doesn't work.
Instead, just use Plek, as that avoids this extra complexity.

Remove extra / for licensify-admin URL

---

features/email_sign_up.feature
features/step_definitions/email_sign_up_steps.rb
features/step_definitions/smokey_steps.rb

There is one end to end test which is from "/foreign-travel-advice/turkey"
to the sign up confirmation page. The rest are from different entry points and stop
after getting to the email frequency page, as from then, the journeys follow a standardised route.
Also removed 'I click ...' step as none of the features were using it.

Add smokey tests for the different email sign up journeys

---

features/email_sign_up.feature

Update in email sign-up are not yet added to staging or production, so
tests will only pass in integration for now.

Add '@pending' to features which skips tests

---

features/step_definitions/csv_steps.rb

We currently test whether Javascript has failed by looking at the wrapper for the "Is there anything wrong with this page" link. We've replaced that feature with the Feedback component so it has stopped working.
This replaces the detection by looking at the `js-enabled` class, which is a better indicator of whether or not there have been Javascript errors.
https://trello.com/c/5ZyHQaB4/139-fix-smokey-test

Fix detection if Javascript has failed

---

features/email_sign_up.feature

Merge after the switch over to notify is complete, removing '@pending' means that these tests will run on all environments to test the new email sign up journeys.

Make email sign up tests active in all environments after change over

---

features/assets.feature
features/step_definitions/signon_steps.rb
features/support/draft.rb

I noticed that visiting draft-assets is currently redirecting us to the internal signon URL instead of the external URL.
Adding this scenario should help us avoid similar problems in future.

Add scenario to ensure draft-assets is protected by signon

---

features/government_frontend.feature

In alphagov/publisher#796 we changed the title from "Prove your
identity to continue" to "How do you want to sign in?" so we need
to update smokey to match this.

Update service sign in feature

---

features/whitehall.feature

The previous asset was returning a 302 which seems to be related to the
parent document it is associated with being unpublished with redirect.
I'm not 100% sure if that behavious is correct or not so raised it with
the asset-management team.
I have though switched this to using a asset of a document that is
published which cuts out a level of ambiguity.

Change the asset whitehall uses for a smokey test

---

features/step_definitions/smokey_steps.rb
features/support/http_requests.rb
features/whitehall.feature

A recent failure in this test highlighted that it hadn't been passing for the right reason: the attachment being requested belonged to an unpublished document and, because [RestClient follows redirects by default][1], we were actually asserting that the resulting document page was a 200.
This test was originally added in c9d72358e97fbdd92c7fe99517fac4b874870dee but there's no indication in the commit note or associated Pivotal Tracker story that we were expecting anything other than to receive the actual attachment directly.
By not following redirects when we make the request for the asset we should avoid similar false positives in future.
[1]: https://github.com/rest-client/rest-client#redirection

Ensure the asset url requested is not redirected

---

features/contacts.feature
features/finder_frontend.feature

Fix failing Smokey tests that check the HMRC contacts finder, which was renamed in https://github.com/alphagov/contacts-admin/pull/372

Update name of HMRC contact finder

---

features/datagovuk.feature
features/step_definitions/datagovuk_steps.rb

Not sure why I have to turn off JS error checking on the second test. 
It seems that visit_path isn't resolving the static assets URLs, causing JavaScript variables to be undefined in inline scripts.
Hopefully this can be ironed out before merging.

Smoke tests for data.gov.uk

---

features/bouncer.feature

We have to access it internally as it not available from the outside except through Fastly.

Access bouncer internally

---

features/support/env.rb

This should be external as the monitoring box doesn't have access via the internal URL.

Use external draft origin URL

---

features/email_sign_up.feature

Update smokey test to match the new design of the taxon pages
Failing test: https://deploy.publishing.service.gov.uk/job/Smokey/7520/console

Fix failing smokey test on taxon page

---

features/step_definitions/whitehall_steps.rb
features/whitehall.feature

Whitehall [PR 3918][1] added functionality to redirect requests for attachments from gov.uk to the asset host. This functionality caused the "Whitehall assets are served" scenario to fail because it was expecting to be able to request an asset without it being redirected.
The fix is to assert that Whitehall attachments _are_ redirected from gov.uk to the asset host, and to separately assert that Whitehall attachments are successfully served from the asset host.
[1]: https://github.com/alphagov/whitehall/pull/3918

Fix failing Whitehall attachments scenario

---

features/step_definitions/smokey_steps.rb
features/step_definitions/whitehall_steps.rb
features/support/http_requests.rb
features/whitehall.feature

These two scenarios started failing in production after we deployed [Whitehall release 13388][1]. This release contains a change that ensures we're redirecting all attachment requests to the asset host.
The scenario titled "Whitehall assets are redirected to the asset host" was failing because the response was cached and we weren't including the "I force a varnish cache miss" step in the scenario.
The scenario titled "Whitehall assets are served from the asset host" was failing because we were expecting to be able to view an asset at assets-origin.publishing.service.gov.uk but we were being redirected to assets.publishing.service.gov.uk. We weren't allowing any redirects as we didn't want a repeat of the problem described in [Smokey PR 345][2].
I've attempted to fix both failures by …

Fix and improve Whitehall attachment scenarios

---

features/travel_advice.feature

With the current Taxonomy changes, it would be easy to break
the hardcoded related content for Travel Advice. This checks
for the existance of the link to the "About" page.

Ensure the related content appears on Travel Advice

---

config/cucumber.yml
features/mirror.feature

The mirror tests are failing on Integration because
it is ignoring the @notaws tag and trying to run the
mirror tests. Now that Integration is on AWS it can
not access the mirrors on Carrenza.
By changing the tag to @notintegration the mirror
tests will not be run on Integration.

Fix mirror failing tests on Integration

---

features/calculators.feature
features/step_definitions/calculators_steps.rb

Related to https://trello.com/c/zrlw5CNd/98-asap-was-missed-in-uprating-add-2017-18-to-child-benefit-tax-calculator-2
Adds a check that the previous tax year is displayed in the calculators form.

Check for previous tax year option

---

features/smartanswers.feature

Don't hit the landing page of a smart answer, because that's rendered by the frontend app, rather than the smart answer app.  Part of this [Trello card](https://trello.com/c/XRXhTtxe/91-improve-smokey-tests-for-frontend-apps-2).

Hit smart answer first questions, not the frontend landing page

---

features/smartanswers.feature
features/step_definitions/smokey_steps.rb

There are no tests for static, so let's look for a meta tag set in https://github.com/alphagov/static/blob/master/app/views/govuk_component/analytics_meta_tags.raw.html.erb.
[Trello card](https://trello.com/c/ikOjBdox/92-add-missing-smokey-tests-for-frontend-apps-2)

Check that smart answers strip postcodes

---

features/step_definitions/government_frontend_steps.rb

This is an attempt to fix: https://deploy.publishing.service.gov.uk/job/Smokey/8124/console
The smokey tests that check the sign-in pages redirect to Goverment Gateway and
Verify are failing in production. We think this is because the default 2 second
max wait time is not enough.
The value for `Capybara.default_max_wait_time` hasn't been overwritten because it
is also being used by the A/B testing tests.

Increase the wait time for sign-in page to redirect

---

features/step_definitions/government_frontend_steps.rb

This should allow us to see if a timeout is happening and allow us to better diagnose a problem.

Raise a timeout exception if timing out

---

features/government_frontend.feature

This will mean they are skipped.
We're seeing problems with these tests at the moment, and while they are investigated we should skip the tests.
[This card](https://trello.com/c/nnAfaJsb/129-reinstate-the-smokey-tests-which-were-failing-and-had-to-be-skipped) is about reverting this change.

Mark two tests as pending

---

README.md
Rakefile
config/cucumber.yml
tests_json_output.sh

Using “~@tag” to exclude tagged tests from running is deprecated. The new syntax is “not @tag”.

Update cucumber tags syntax

---

README.md
features/email_sign_up.feature
features/feedback.feature
features/finder_frontend.feature
features/gov_uk.feature
features/info_frontend.feature
features/javascript_errors.feature
features/mainstream_publishing_tools.feature
features/manuals-frontend.feature
features/signon.feature
features/step_definitions/smokey_steps.rb
features/whitehall.feature

This commit makes some stylistic changes to test definitions that don’t affect the tests themselves.

Make some stylistic changes

---

features/collections.feature
features/publicapi.feature
features/router.feature
features/whitehall.feature

whitehall no longer serves `/api/organisations` or organisation home pages (now served by collections). It also doesn’t serve organisation short URLs, which should be tested as part of the router tests.

Move tests from whitehall to other apps

---

features/step_definitions/ab_testing_steps.rb
features/step_definitions/benchmark_steps.rb
features/step_definitions/calculators_steps.rb
features/step_definitions/collections_steps.rb
features/step_definitions/datagovuk_steps.rb
features/step_definitions/draft_environment_steps.rb
features/step_definitions/finder_frontend_steps.rb
features/step_definitions/frontend_steps.rb
features/step_definitions/mirror_steps.rb
features/step_definitions/search_steps.rb
features/step_definitions/smokey_steps.rb

The “should” syntax is deprecated and has been replaced with the “expect” syntax.

Use new “expect” syntax rather than “should”

---

features/step_definitions/licensing.rb
features/support/base_urls.rb

This commit makes tests on `licensify-admin` with others, where the default path is defined centrally.

Make licensify-admin consistent with other paths

---

features/asset_manager.feature
features/bouncer.feature
features/draft_environment.feature
features/feedback.feature
features/government_frontend.feature
features/javascript_errors.feature
features/licencefinder.feature
features/mirror.feature
features/performance_platform.feature
features/search.feature
features/service_manual.feature
features/topics.feature
features/whitehall.feature

This commit mostly puts tags on one line to make them consistent, and adds `@normal` tags to tests that didn’t have any tags.
`@high` tags are added to tests that look for XSS vulnerabilities.
One test tagged `@ disabled_in_icinga` is now tagged `@normal` since there’s no reason for it to be ignored by Icinga.
Tests for Government Gateway redirects are now made live.

Make tags consistent

---

features/support/base_urls.rb

This was causing tests for licensing-admin to fail since that apps doesn’t normalise more than one consecutive slash.

Remove extra slash

---

features/ab_testing.feature
features/asset_manager.feature
features/calculators.feature
features/calendars.feature
features/collections.feature
features/contacts.feature
features/csv.feature
features/datagovuk.feature
features/licencefinder.feature
features/performance_platform.feature
features/publicapi.feature
features/router.feature
features/search.feature
features/service_manual.feature
features/smartanswers.feature
features/whitehall.feature

This commit cleans up the existing tests in a number of ways:
* Moves repeated steps within tests into “background” sections in each feature
* Standardises naming and spacing
* Removes some checks for HTTP status where we are also testing for other measures of success

Clean-up tests

---

features/search.feature
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

This commit changes tests that use the search engine to cache bust with the `c` query string param (which is recognised by rummager) as opposed to `cache_bust` (which is not, but which is more descriptive).

Fix search cache busting

---

features/publicapi.feature

`/api/search.json` needs to use `c` rather than `cache_bust` for cache busting.

Cache bust correctly for search API

---

features/asset_manager.feature
features/assets.feature
features/frontend.feature
features/gov_uk.feature
features/smartanswers.feature
features/whitehall.feature

This commit removes status code checks when they use the PhantomJS stack rather than the rack-test stack. Selenium does not support status code checks, so these will break once we switch. In addition, these checks are better made by looking for strings on the resulting page.

Remove status code checks

---

features/datagovuk.feature
features/javascript_errors.feature
features/licensing.feature
features/step_definitions/smokey_steps.rb

Reverts alphagov/smokey#391
This was causing issues that will be fixed with the upcoming move to Chrome but I don't want to cause more alerts for the time being.

Revert "Remove ignoring of JavaScript errors"

---

Rakefile

This commit updates the rake tasks to supply an environment.

Update rake tasks

---

Rakefile

This commit turns on more detailed logging of Smokey’s progress while running tests via the rake tasks.

Show Smokey progress when running rake tasks

---

features/support/env.rb

This commit makes Chrome run in headless mode so that it works when run in an automated fashion.

Make Chrome headless

---

features/support/env.rb

This commit sets a Chrome preference to ignore SSL errors during tests. This happens because headless Chrome doesn’t seem to support the same root certificate providers as Chrome in normal mode.

Ignore SSL errors

---

features/support/env.rb

This makes it into the JSON output, making it invalid.

Remove proxy log message

---

features/finder_frontend.feature

This commit fixes a test which started failing after https://github.com/alphagov/finder-frontend/pull/552. It also adds a step to check for an open facet to another test.

Fix finder-frontend test when checking facets

---

features/support/hooks.rb

This commit changes the JS error logger to send error messages to `$stderr` rather than the default of `$stdout`. This should prevent the messages from appearing at the top of the Smokey loop JSON file and breaking it. They will still appear inside the JSON as an issue so will be flagged up.

Send JS errors to $stderr

---

features/gov_uk_redirect.feature

This scenario has been failing for a week or so with the error:
`Failed to open TCP connection to service.gov.uk:443 (Connection refused...`

Disable failing scenario

---

features/support/env.rb

https://trello.com/c/ftCfaDhf/452-investigate-frequent-smokey-youtube-error
Fixes proxy configuration for Selenium chrome driver using the appropriate chrome option 'directly'.
See https://www.chromium.org/developers/design-documents/network-settings
The failing feature is `features/government_frontend.feature` as the page containing a Youtube video (youtube urls should be blacklisted as per the env config) is https://www.gov.uk/government/case-studies/out-of-syria-back-into-school
example fail: 
https://deploy.staging.publishing.service.gov.uk/job/Smokey/10362/console

Fix proxy server config for chrome driver

---

features/support/env.rb

https://trello.com/c/ftCfaDhf/452-investigate-frequent-smokey-youtube-error
Simplifies the `proxy-server` option value.

Simplify proxy configuration

---

features/finder_frontend.feature
features/step_definitions/whitehall_steps.rb
features/whitehall.feature

The policy pages have now been replaced by the Topic Taxonomy, so
remove the tests as the policy pages are now being removed.

Remove tests related to policies

---

features/email_sign_up.feature

As the policy pages are going to be unpublished. They are being
replaced by the topic pages.

Remove a test for a policy page

---

features/publishing_tools.feature

It's going to be turned off, as the policy pages are being replaced
with topic pages.

Remove test for Policy Publisher

---

Gemfile
Gemfile.lock
features/support/env.rb

Currently Smokey is failing on Integration, probably because it can't
run chromedriver. The machine has chromedriver installed, but because
of the chromedriver-helper gem, this won't be used. Therefore, check
if chromedriver is available, and if it is, use it, rather than
loading chromedriver-helper.

Use chromedriver from the path if available

---

bin/browsermob-proxy

This avoids having a separate shell process sitting around.

Use exec to run browsermob-proxy

---

features/foreign_travel_advice.feature

This PR removes the dependency on related links for the test scenario _Check a country page loads correctly_. Related links are changeable pieces of content and therefore should not be directly tied to the automated tests which check our production environment is operational.
This was raised from the recent A/B tests around related links, which for the B variant of this test has removed the related link being relied upon.
Solo: @karlbaker02

Remove test dependency on related links for foreign travel advice pages

---

features/smartanswers.feature

Due to behaviour changes in smart answer, various examples for for reporting lost or stolen passports no longer work. These examples fails and have been removed has they serve no purpose.

Remove failing examples for smart answers

---

features/gov_uk.feature

Both these cases should now return protocol-relative redirects.

Test correctly for trailing slashes and full stops

---

features/gov_uk_redirect.feature

Everything should eventually redirect to www.gov.uk with HTTPS and HSTS headers.

Check all redirects for HSTS headers

---

config/cucumber.yml
features/calendars.feature
features/contacts.feature
features/frontend.feature
features/government_frontend.feature
features/router.feature
features/search.feature
features/smartanswers.feature
features/whitehall.feature

Since the migration, our Carrenza machines can no longer access GOV.UK
staging. This limits checks that rely on access to GOV.UK staging to
only run on AWS machines. Even though this isnt' an issue in production,
because we don't limit access to www.gov.uk, it makes sense to not run
these checks there as there's no companion environment to debug them in.

Limit 'www' frontend checks to only run on AWS

---

features/step_definitions/search_steps.rb

`.js-options-container` is now expected.
This will resolve critical alerts on production.
See https://github.com/alphagov/finder-frontend/blob/master/app/views/components/_option-select.html.erb#L33

Add expected class to option-select component

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

This checks that the dataset count in CKAN closely matches the dataset count in the data.gov.uk Find frontend. This is because sometimes the syncing process can fail between CKAN and Find, and this test should alert us to that fact quickly.
[Trello Card](https://trello.com/c/TGd6sSbe/904-add-a-smokey-check-for-the-number-of-datasets-in-datagovuk-find)

Add a Smokey test for data.gov.uk dataset count

---

features/step_definitions/search_steps.rb

Search tests were failing because they were looking for `.results-list li a`. The old site search results page has been replaced by the All Content finder, which has `.finder-results li a`

Fix smokey for new site search finder

---

features/whitehall.feature

This page is now served by finder-frontend

Remove the consultations finder from the whitehall tests

---

features/step_definitions/whitehall_steps.rb

This is now in finder-frontend, which has slightly different HTML.

Change "view publications" step for migrated finder

---

Rakefile
features/support/env.rb

These are run by the Smokey job in Jenkins https://github.com/alphagov/govuk-puppet/commit/ebb986a591d402c735456741cd74e1560dab0816 but the job itself doesn't currently exist.
[Trello Card](https://trello.com/c/d5e240P1/873-fix-smokey-in-aws)

Add AWS variations of the test Rake tasks

---

features/email_sign_up.feature

This process has changed and the test wasn't updated with it. This and https://github.com/alphagov/smokey/pull/506 should fix the two email sign up tests which are currently failing in production.

Fix failing test related to email signups

---

features/gov_uk_redirect.feature

These headers are only returned from the https version of gov.uk not the plain http versions.
[Mozilla's information about HSTS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Description) states:
> The `Strict-Transport-Security` header is ignored by the browser when your site is accessed using HTTP; this is because an attacker may intercept HTTP connections and inject the header or remove it. When your site is accessed over HTTPS with no certificate errors, the browser knows your site is HTTPS capable and will honor the `Strict-Transport-Security` header.

Don't check for HSTS headers in non-https

---

features/step_definitions/finder_frontend_steps.rb

This was changed in https://github.com/alphagov/finder-frontend/commit/b6f42dfe6b318e0937d963591c5c0600826dc5ae but the Smokey tests weren't updated. The class name is now prefixed with `js-`.
[Trello Card](https://github.com/alphagov/finder-frontend/commit/b6f42dfe6b318e0937d963591c5c0600826dc5ae)

Fix finder facet selector

---

features/email_sign_up.feature

The old /government/publications route has been replaced by a redirect to search and is no longer available as Whitehall finder. /government/statistics still exists as a finder so we can switch to using that one.

Fix email sign up

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

This improves the speed by using the quicker search endpoint and improves the accuracy of the dataset count test.

Improvements to data.gov.uk tests

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

It turns out there are multiple ways of counting the number of datasets in CKAN:
- https://ckan.publishing.service.gov.uk/api/3/action/package_search
- https://ckan.publishing.service.gov.uk/api/3/search/dataset
- https://ckan.publishing.service.gov.uk/api/3/action/package_list
Each one gives a slightly different package count. This is because some of them get their data from Solr and some of them get it from Postgres. Solr is meant to be an accurate representation of the Postgres database, but there are no guarantees and sometimes it can end up out of sync. By using the Postgres count, we'll get the most accurate value.
[Trello Card](https://trello.com/c/FkQuWu3i/943-investigate-datagovukpublish-being-unable-to-access-ckan-api-sometimes)

Use more accurate dataset count

---

features/feedback.feature

The /contact/foi page has been replaced with a redirect to /make-a-freedom-of-information-request which has a different title.
See https://github.com/alphagov/feedback/pull/703 for more information.

Update text to search for on FOI page

---

features/assets.feature

`assets-origin` is not the correct domain for this since the AWS migration. It should be just `assets` which goes through Fastly. This is similar to `www` vs `www-origin`. Example:
- https://assets.publishing.service.gov.uk/media/513a0efbed915d425e000002/120613_Albania_Travel_Advice_WEB_Ed2_jpeg.jpg
- https://assets-origin.publishing.service.gov.uk/media/513a0efbed915d425e000002/120613_Albania_Travel_Advice_WEB_Ed2_jpeg.jpg

Use assets domain for checking asset-manager

---

features/smartanswers.feature

The email address is no longer present on https://www.gov.uk/register-a-death/y/overseas/north-korea/same_country
Resolves https://alert.production.govuk.digital/cgi-bin/icinga/extinfo.cgi?type=2&host=ip-10-13-5-163.eu-west-1.compute.internal&service=Run+smartanswers+normal+priority+tests

Fix expected smartanswers text

---

features/service_manual.feature

The 'Digital' has been dropped from the name.

Update following service standard rename

---

features/email_sign_up.feature
features/step_definitions/email_sign_up_steps.rb

Trello card: https://trello.com/c/rUqtUSMG
- Verifies that the business finder email signup is 'No more than once a day' by default.
- Verifies that other existing email signups continue to be 'As soon as they happen' by default.
In https://trello.com/c/f7DWeg4q, we changed the default value of the business finder email screen to daily. As this touched email-alert-frontend and finder-frontend, we were able to test in isolation but not as a whole, so an integration test is required to check the e2e functionality.
We also want to verify that we haven't broken the default value of existing email signup pages.

Email default frequency

---

README.md

The [GDS Way Java guidance](https://gds-way.cloudapps.digital/manuals/programming-languages/java.html) has been updated with [a preference for AdoptOpenJDK](https://github.com/alphagov/gds-way/pull/276/commits/18025ccd).

Prefer AdoptOpenJDK over OpenJDK

---

README.md

Command worked on the basis that the browsermob process would be the first thing in the grepped output, and the grep command itself would be the second thing. But when stored as an alias, the grep command is the first thing and the browsermob process is the second thing.
Changing browsermob -> [b]rowsermob ensures that the browsermob process is still found ("find the first b followed by rowsermob"), but that the grep process itself isn't matched.
Secondly, the \$2 was getting evaluated too early, so the ID wasn't being grabbed properly. That is now escaped."

Fix 'killbrowsermob' alias

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

- Check that it is an organogram page by relying on the
'View the full organogram' text of the button
- Check that we don't get any errors similar to:
```
Refused to connect to
'https://s3-<organogram bucket>.csv' because it violates the following
Content Security Policy directive: "connect-src...".
```
Co-Authored-By: Ken Tsang <ken.tsang@digital.cabinet-office.gov.uk>
https://trello.com/c/wh8pUMOm/982-fix-display-of-organogram-visualisations-on-datagovuk

Add s3 CSP test for organograms previews

---

features/email_sign_up.feature
features/gov_uk.feature
features/step_definitions/whitehall_steps.rb
features/whitehall.feature

This PR removes tests which are specific to the Whitehall publications finder, which is being removed as it does map directly to any of the new finders.
Tests for existing documents rendered by `government-frontend` and including the URL `/government/publications/path/to/doc` will continue to be rendered in this way, so these tests are not removed in this commit.
Trello: https://trello.com/c/3BuGZK2A

Remove Whitehall publications finder from tests

---

features/finder_frontend.feature
features/step_definitions/smokey_steps.rb
features/support/env.rb

Add XSS tests for finder frontend.
Attempts a number of the "naughty strings",
https://github.com/minimaxir/big-list-of-naughty-strings to see
if finder-frontend can be forced to run javascript to display
an alert.
This tests inputting text in the keywords text field through javascript 
and by submitting the keywords through the URL
Trello: https://trello.com/c/eaa0vKa2/726-add-tests-for-xss-in-text-fields-in-finder-frontend-and-smokey-l

Add finder frontend XSS tests

---

features/search.feature
features/step_definitions/search_steps.rb
features/support/env.rb
features/support/hooks.rb

This PR merges the three "Check search results for <keywords>" tests we had, and extends them.  This is what happens now:
1. As before:
1. A search is done
1. Checks that (a) there are results and (b) that they're unique
1. New:
1. Checks that a request is made with `dp=%2Fsearch%2Fall%3Fkeywords%3D...` in the URL
1. Clicks the "show more search options" link
1. Checks that a request is made with `eventCategory=filterClicked` in the URL
1. Clicks the "next page" link
1. Checks that a request is made with `eventCategory=contentsClicked` in the URL
1. Clicks the top result (on the second page of results)
1. Checks that a request is made with `eventCategory= navFinderLinkClicked&eventAction=Search.1` in the URL
To make this work I had to do a little refactoring of how request logging works, …

Add tests for search analytics

---

features/finder_frontend.feature
features/step_definitions/search_steps.rb
features/step_definitions/smokey_steps.rb
features/support/env.rb
features/support/hooks.rb

This is raised to address problems we have been seeing from 2nd line regarding the recently added Finder Frontend XSS tests: https://github.com/alphagov/smokey/pull/533
This does some work to reduce the time these tests take to run by about 4-5 seconds per test, it adds a greater timeout to try stop the tests failing as often as they do, and it reduces the amount of tests as these seem too thorough for something testing at an end-to-end level.
Further details in commit messages.

Reduce quantity of finder frontend XSS tests and address flakiness

---

features/search.feature
features/step_definitions/search_steps.rb

These tests are flaky, but I've not been able to replicate that
locally.  Failures seem to often be when checking for the
"filterClicked" event, so I suspect there's not enough time between
the search options being expanded and the check for the request, as
the request is asynchronous.
So I've just moved all the checks to the end.

Re-order search analytics tests to check at the end

---

features/data_gov_uk.feature

We have CKAN running in integration, staging and production but DGU only runs in production. This tests CKAN in each environment but specifies not to run DGU tests in integration or staging since they're only testing production.

Test CKAN in all envs, only test DGU in production

---

features/search.feature
features/step_definitions/government_frontend_steps.rb
features/step_definitions/search_steps.rb
features/support/delay.rb

Checking for the async analytics requests is pretty flaky.  Moving them to the end, after all the sync requests, hasn't helped.  So instead use the `wait_until` function from the government-frontend step definitions to wait until the request has been made.  There is a max delay of 5s.
---
[Trello card](https://trello.com/c/u7D6Yx0c/770-fix-flaky-search-analytics-test)

Use the "wait-until" logic for search analytics checks

---

tests_json_output.sh

This script doesn't manage the cucumber process properly, so just
remove that as a concern, Upstart can do this. Also, use exec to avoid
having the bash process stick around, and use the --out option for
cucumber to write the output file, as this avoids redirecting the
output through bash.

Simplify tests_json_output.sh

---

features/email_sign_up.feature

The "create subscription" page was recently updated to allow users to filter their
subscriptions, so we need to select at least one checkbox.
See: https://deploy.blue.production.govuk.digital/job/Smokey/1030/console

Update failing business finder tests

---

features/step_definitions/feedback_steps.rb

This test was failing because it was failing the browser validation on input fields
of type="email". This step removes the browser validation from the email field, forcing
the backend validation to run.

Test backend validation on email field

---

features/caching.feature
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

This adds a few small checks that caching works
It checks only the homepage, and that post requests
aren't cached.
At the moment CDN changes aren't checked specifically
by the smoke tests.
Trello: https://trello.com/c/IPbLTDLq/806

Add smoke tests for cache

---

features/mirror.feature
features/step_definitions/mirror_steps.rb

The Mirror feature was previously disabled in 2d3f792a4fa4f651f763c49f6566495425ed78fd
when the mirrors were migrated to S3. We are adding the tests back,
refactored to work with S3.

Add S3 Mirrors tests

---

features/mirror.feature
features/step_definitions/mirror_steps.rb

We are seeing:
```
Given S3 mirrors
Your block takes 1 argument, but the Regexp matched 0 arguments.
features/step_definitions/mirror_steps.rb:1:in `/^S3 mirrors/'
```
Disable mirror tests on integration/staging/training, only
production instances have access to the mirror buckets.

Fix mirror feature

---

features/email_sign_up.feature

This commit changes the wording that is looked for on email signup pages for frequency from "no more than once a week" to "once a week" to reflect wording improvements.

Update frequency wording for email alert signups

---

features/step_definitions/mirror_steps.rb

Use simple HTTP requests when using S3

Fix Mirrors 400 bad request

---

features/content_data_admin.feature

The word 'data' has been capitalised in the name as of https://github.com/alphagov/content-data-admin/commit/557b828ea4f2d63dba6cbc5a8b063e0859b00ebe.

Fix name of Content Data

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

https://trello.com/c/Au6s6UMP/639-smokey-tests-failing-in-all-environments-various-reasons
Previously we experienced an issue where a significant number of
datasets disappeared from the DGU Find frontend due to a suspected API
discrepancy from CKAN. We added two features to detect this issue in
future, but one requires manual intervention to keep the check accurate.
This removes the accuracy feature, since we believe it is covered by the
other feature we added to check the agreement between the number of
datasets reported by CKAN vs. DGU Find. In particular, there is no
evidence that the total count of datasets reported by CKAN was at fault.
https://github.com/alphagov/smokey/pull/493

Remove absolute check on DGU datasets

---

features/step_definitions/waf_steps.rb
features/support/http_requests.rb
features/waf.feature

the default web acl in place on the cache ALB has a rule that blocks
traffic if the header X-Always-Block: true is set on a request. We can
use this as an basic sanity check that the waf is associated with the
ALB and as a initial example test for others to follow as more rules are
added.
:warning: requires: https://github.com/alphagov/govuk-aws/pull/1051

adds test to ensure default web acl rule in place

---

features/step_definitions/waf_steps.rb
features/support/http_requests.rb
features/waf.feature

The WAF feature is currently failing with "undefined" errors:
```
1 scenario (1 undefined)
3 steps (2 undefined, 1 passed)
0m20.382s
You can implement step definitions for undefined steps with these snippets:
When("I send a GET request to \/") do
pending # Write code here that turns the phrase above into concrete actions
end
Then("the response status should be {int}") do |int|
pending # Write code here that turns the phrase above into concrete actions
end
```
This should fix the undefined errors.

Fix issues with WAF feature

---

nagios_check_cache.py

This partially reverts e12e983b46d483d9d595bdd704f5c7964fc678b0 to restore the previous behaviour of sending an OK status to Icinga when no tests were run (rather than an UNKNOWN which I had changed it to). This is because when no tests are run it means the feature has no tests at the priority, not that there is a problem.
[Trello Card](https://trello.com/c/jpFVXZth/1146-make-icinga-generate-unknown-result-on-missing-feature-file)

Don't show an unknown if there are no tests

---

features/benchmarking.feature

As it tries to connect to Bouncer internally, which only works in AWS.

Mark the Bouncer benchmarking to just run in AWS

---

features/search.feature
features/step_definitions/search_steps.rb
features/support/hooks.rb

Paired with @hannako 
We are now sending a different request for tracking,
so this ensures we check this stuff correctly in the
smoke tests.
Related: https://github.com/alphagov/static/pull/1800
Trello: https://trello.com/c/YXkJcbBo/851

Make analytics tests check for body

---

features/step_definitions/draft_environment_steps.rb

There is a long standing bug [1] in the YouTube embed via their API.
The page will still work for users, as will the video, but the
Javascript error is causing Smokey to break. We have tried various
suggested mitigations and fixes but none have worked.
As the test is only really testing the draft stack and not videos,
switching out the test page for one without a Youtube video seems a
sensible change.
[1] https://issuetracker.google.com/issues/35174286

Suppress JS error for YouTube embed

---

features/draft_environment.feature
features/step_definitions/draft_environment_steps.rb

The previous commit changed the candidate page for draft stack
but didn't include updating the spec file itself and is pointing
to a newly published page that does not yet exist on integration.

Fix feature tests for draft pages

---

features/feedback.feature
features/step_definitions/feedback_steps.rb

https://github.com/alphagov/govuk_publishing_components/issues/997
This adds a scenario to check a user is able to successfully submit a
request to give feedback when they don't find a page is useful. While
this feature exists on most pages on GOV.UK, this check only visits the
homepage to superficially cover the behaviour.
Co-Author: @bilbof

Add scenario for when a page is not useful

---

features/data_gov_uk.feature

Smokey tests for DGU are failing on Integration as the Integration website needs basic auth, so adding the basic auth headers should fix them.

Add basic auth headers to DGU test

---

features/benchmarking.feature
features/email_sign_up.feature
features/gov_uk.feature

The Whitehall statistics finder is soon to be redirected to the newer
https://gov.uk/search/research-and-statistics finder. I've updated tests
that will fail when that redirect goes in.
There is one remaining test that should be updated (the Whitehall tests for
announcements and statistics atom feeds).  This test will continue to pass
once the redirects are deployed, but should be tweaked to ensure that the
redirects are actually working.
https://trello.com/c/BE2ooOcY/934-redirect-whitehall-statistics-finder-to-finder-frontend

Update tests for retiring stats finder

---

features/frontend.feature
features/step_definitions/analytics.rb
features/step_definitions/search_steps.rb
features/support/env.rb

This adds a test to ensure that visiting the homepage triggers a Google Analytics `t=pageview` event.
I've also blacklisted requests to Google Analytics to prevent the request from affecting our real results.
[Trello Card](https://trello.com/c/tpj7DUOs/1187-add-smokey-test-to-check-were-communicating-with-google-analytics)

Make sure page view tracking events are sent on the homepage

---

features/draft_environment.feature
features/step_definitions/draft_environment_steps.rb
features/support/env.rb

I think this should solve the YouTube problem we were seeing before as all requests to that address should result in a 200 successful response.
This allows us to revert 4480e78 and go back to using the old case study which had an embedded YouTube video.

Add youtube-nocookie to the proxy blacklist

---

features/draft_environment.feature
features/step_definitions/draft_environment_steps.rb
features/support/env.rb

Reverts alphagov/smokey#585
Ended up causing feature failures in smokey so I'm reverting it.

Revert "Add youtube-nocookie to the proxy blacklist"

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

A previously tested endpoint is no longer exposed in the API.
An alternative method can be used to obtain the same information from the frontend.

Change DGU steps to collect package count from frontend

---

features/benchmarking.feature

- The current time limit is causing the Smoke tests to be flapping in
Carrenza production.
- Doubling the time is not in the spirit of benchmarks, but desirable
to reduce noise in alerting. This is a ticket, not a critical.

Up benchmark time limit for research-and-statistics

---

features/brexit_check.feature
features/step_definitions/brexit_check_steps.rb

This adds basic tests the Brexit check rendered by finder-frontend.

Add smoke tests for Brexit checker

---

features/step_definitions/search_steps.rb

Following [this change in Finder Frontend to use a button element rather than a link](https://github.com/alphagov/finder-frontend/pull/1542), the Smokey tests have been failing because it still expects the toggle to be a link:
```Unable to find link "+ Show more search options" (Capybara::ElementNotFound)```
This updates the test to click on a button element rather than a link.

Use click_button for show more search options

---

features/benchmarking.feature

We occasionally get a failure for these tests when they are run in carrenza, which we think is related to network latency.  We've checked the finder-frontend application logs and the maximum time to respond hasn't exceeded 1.6 secs for the research and statistics finder in this period.
These tests should be failing if the software is slow, not if there are problems with network connectivity.

Run finder benchmarking tests in AWS only

---

features/support/visiting_pages.rb

This will make requests made via Smokey easier to spot in logs that may not report on user-agent

Add "smokey" to cache-bust string

---

features/step_definitions/brexit_check_steps.rb

The brexit checker content changed in https://github.com/alphagov/finder-frontend/pull/1706/commits/f74c7c192c21daa7a5a0ae1041ff40aacff2fe29
Update smokey's tests to reflect this.

Update brexit checker content

---

features/step_definitions/finder_frontend_steps.rb

This resolves the failing test due to changes in https://github.com/alphagov/finder-frontend/pull/1713.

Update heading for specialist finders

---

features/step_definitions/email_sign_up_steps.rb

Making this change as some tests were out of date, and were unable to pick between multiple occurrences of the same link - now they'll use the first one they find.

Change email singup test to use first link on page

---

features/email_sign_up.feature
features/step_definitions/email_sign_up_steps.rb

Trello: https://trello.com/c/KYrvoZmz/306-double-opt-in-stop-preselecting-the-frequency-when-subscribing
Relates to: https://github.com/alphagov/email-alert-frontend/pull/624/commits
In https://github.com/alphagov/email-alert-frontend/pull/624/commits we are stopping the preselection of email frequency when users sign up for new subscriptions. We can therefore remove the tests associated with this functionality.

Remove check for email frequency preselection

---

features/search.feature
features/step_definitions/search_steps.rb

Removing a bit of the search test because we're not showing the "Show more search options" link at present.

Search options are always shown

---

features/email_sign_up.feature
features/step_definitions/email_sign_up_steps.rb

https://trello.com/c/2Rjx8ib3/307-double-opt-in-simplify-smokey-tests-for-email-subscriptions
This removes a couple of steps from one of the email signup scenarios,
which went beyond the 'signup' journey and through the 'subscribe'
journey, which will shortly change with the introduction of double
op-in. The interaction between double opt-in and a received email means
we can't preserve an E2E smokey test for subscriptions, but we're
comfortable this is covered by the of specs in the respective repos.

Remove email signup steps for double opt-in

---

features/finder_frontend.feature

Revert of #626 where we temporarily disabled the step as we were running an AB test.
[Trello card](https://trello.com/c/1nHm6AeM/603-revert-keyword-facet-tags-a-b-test)

Reenable search keyword test step

---

features/search.feature

This is now failing following the change to cookie consent.  I think
we still want this test, so rather than remove it outright I've
disabled it until we make smokey accept cookies.

Mark search analytics test as @pending

---

features/frontend.feature

This is now failing due to the recent cookie consent changes.
Disabling it for now until it's revised later.

Mark homepage analytics test as @pending

---

features/step_definitions/smokey_steps.rb

These were removed in https://github.com/alphagov/finder-frontend/pull/1863

Remove keyword facet tag check

---

features/brexit_check.feature
features/step_definitions/brexit_check_steps.rb

We recently reslugged the brexit checker. This commit reflects that
trello: https://trello.com/c/LllJV5JJ/409-reslug-the-brexit-checker

Update the brexit checker route to transition-checker

---

features/email_sign_up.feature
features/step_definitions/brexit_check_steps.rb

We have updated some copy and removed the checker previously at `/find-eu-exit-guidance-business`, so these tests can be updated

Update transition related tests

---

features/search.feature
features/step_definitions/search_steps.rb

Two commits: The new cookie window was preventing any visits to the search page from
allowing any actual searching to take place. Small fix in place to allow us to bypass the window through accepting the cookies.
Also updated the relevant feature to remove some obsolete functionality.
Trello: https://trello.com/c/mWtEFWK9/1334-make-smokey-consent-to-search-cookies

Update search tests to allow cookies

---

features/licence_finder.feature

This came out as an incident review action.
It tests the following page:
Trello card: https://trello.com/c/hTX3K6RQ/1740-2-add-a-smokey-test-for-applying-for-a-licence-with-a-postcode

Add test for licence postcode lookup

---

features/ab_testing.feature
features/search.feature
features/step_definitions/ab_testing_steps.rb
features/step_definitions/search_steps.rb
features/step_definitions/smokey_steps.rb
features/support/http_requests.rb

The "And I consent to cookies" step adds the consent cookie to all
following requests, whether Capybara requests in the current
session (using "visit" etc) or raw HTTP requests (using
"do_http_request" etc).
Consent can be revoked by setting @consent_cookie_value to nil, but
there are no tests yet which give and then revoke consent.
Also change search tests to use this new way, and A/B test tests to
consent.

Make cookie consent global

---

features/step_definitions/smartanswers_steps.rb

The CSS classes on the country drop-down list was updated in
https://github.com/alphagov/smart-answers/pull/4324
This updates the relevant step to target the correct class.

Update Smartanswers country step to new class selector

---

features/support/env.rb

Our PAs find it tricky to omit Smokey traffic from our analytics.  This is more important than it used to be because of our reduced analytics traffic.
This sets the Chromedriver user agent to be the same as the [user agent used by RestClient](https://github.com/alphagov/smokey/blob/master/features/support/http_requests.rb#L72) for some of the other Smokey requests.
https://trello.com/c/BC2lVBbw/1372-use-a-smokey-specific-user-agent-or-other-identifier

Set Chrome user agent to Smokey Test / Ruby

---

features/data_gov_uk.feature

The dataset seems to have been renamed. I'm not sure if the test is
doing what it should be, as the response is a redirect to a HTML page
rather than some nice RDF, but that's maybe another issue.

Update a test dataset in the data.gov.uk feature

---

features/email_sign_up.feature

The sign up button is a button, not a link.
https://www.gov.uk/email-signup?link=/government/organisations/department-for-education

Correct link to button

---

features/step_definitions/search_steps.rb

As we show parts in search results now, this step can fail if a part
has the same title as a normal result, as capybara doesn't know which
to click.
So the solution is to call `click` on the right element directly,
keeping it to proper results (not parts) by adding the class: parts
are a .gem-c-document-list-child__link, and so don't match.

Fix ambiguous search result error

---

features/email_sign_up.feature

This is similar to https://github.com/alphagov/smokey/pull/659 but for a transport taxon. I'm not sure why we've only had to change it now.
https://www.gov.uk/email-signup?topic=/topic/transport/motorways-major-roads is the page we get to with the "Sign up" button.

Fix sign up link text

---

features/benchmarking.feature
jenkins.sh

https://trello.com/c/VdbPVqto/154-support-running-only-smokey-tests-that-are-relevant-to-an-app
These should only be run by the "test_json_output" script.
Accidentally removed in: 4d73195

Fix missing tag to skip benchmarking scenarios

---

features/smartanswers.feature

https://trello.com/c/VdbPVqto/154-support-running-only-smokey-tests-that-are-relevant-to-an-app
This tag needs to match the TARGET_APPLICATION parameter used by
the 'Deploy_App_Downstream' job. Normally this would equal the
repo name, but Smart Answers has a historical inconsistency.

Fix hyphen typo in 'app-smart-answers' tag

---

features/publishing_tools.feature

the publishers have been moved to AWS

run publishing tools in AWS only

---

README.md
docs/troubleshooting.md
docs/writing-tests.md
features/support/http_requests.rb

This rewrites the README to make it easier to add further
documentation about the use of tags in this repo.
Please see the commits for the individual changes and the
reasons for some of them.

Rewrite the README to support further changes

---

jenkins.sh

This should only happen if the test code has been written incorrectly;
not setting this means the tests pass when they shouldn't.
Tripped me up when doing [1].
[1]: https://github.com/alphagov/smokey/pull/688

Fail the test run if there are undefined step

---

features/step_definitions/brexit_check_steps.rb

The start page has now been redirected to the /transition page now, so we should start from there instead.

Update the brexit checker test

---

features/step_definitions/brexit_check_steps.rb

The job is still failing so hopefully this is the reason why. Following on from https://github.com/alphagov/smokey/pull/697
```
Unable to find link "Check what's changing" (Capybara::ElementNotFound)
./features/step_definitions/brexit_check_steps.rb:3:in `"I start the checker"''
```
Failing job: https://deploy.blue.production.govuk.digital/job/smokey/4093/console

Use different apostrophe for link text

---

features/support/base_urls.rb

This is confusing and unnecessary for internal URLs. Ideally we
should drop the defaults for external URLs as well (because it's
so surprising), but that would require more extensive changes to
features that are relying on the defaults.

Remove path defaults for internal URLs

---

features/data_gov_uk.feature

https://trello.com/c/MjU2qdeI/228-enable-smoke-tests-on-staging
This should hopefully detect whether ckan's solr is up & running too.

data.gov.uk: add test of CKAN action api's search ability

---

.github/pull_request_template.md
README.md

Tripped me up on: https://github.com/alphagov/smokey/pull/692
> This app doesn't have CI setup, and it would be misleading to do so:
> the behaviour of the tests changes depending on the environment they
> are run in.
> The manual [Smokey job][] will pick up …

Add a PR template to encourage manual testing

---

features/step_definitions/feedback_steps.rb

When testing the "Is this page useful?" feature, the Feedback application submits an
e-mail address to the GOV.UK Notify service.
In Integration and Staging these Notify services are trial accounts with "allow lists". 
An e-mail address not on their guest list will result in an unsuccessful request.
This change will allow this test to simulate a successful submission to the
service.
https://docs.notifications.service.gov.uk/ruby.html#smoke-testing

Swap Feedback feature's generic test e-mail address with Notify test address

---

features/step_definitions/datagovuk_steps.rb

Selenium can't use the selector with the bang as chrome will reject it
as an invalid selector. It turns out we don't need to use this selector
to get the span and can retrieve the number from the parent element.
Steps to deploy …

Fix invalid selector

---

features/licensing.feature
features/step_definitions/smokey_steps.rb
features/support/hooks.rb

We're currently unable to deploy changes to Licensify. Our
Smokey test suite is failing because we're seeing CSP errors
on Google Analytics requests in Licensify.
In order to get Smokey passing again - essential for continuous
deployment and for developer confidence - we've decided to
ignore the JS error for these tests. When we're able to
deploy Licensify again, we should already have fixed the CSP
issue here:
https://github.com/alphagov/licensify/pull/492
Example steps to test …

Suppress JS console errors in Licensify tests

---

features/licence_finder.feature

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This removes a feature for a page that's actually rendered by
"frontend", which always has tests for postcode lookup.
Steps to deploy a …

Remove redundant (frontend) feature

---

features/coronavirus_local_restrictions.feature
features/step_definitions/coronavirus_local_restrictions_steps.rb

Trello: https://trello.com/c/rQaK8bpe
Add test for Coronavirus local restrictions postcode checker
https://deploy.integration.publishing.service.gov.uk/job/Smokey/23492/console
```
@app-collections
Feature: Collections
Background:                                 # features/coronavirus_local_restrictions.feature:4
Given I am testing through the full stack # features/step_definitions/smokey_steps.rb:19
And I force a varnish cache miss          # features/step_definitions/smokey_steps.rb:26
Scenario: Postcode checker shows results                # features/coronavirus_local_restrictions.feature:8
When I visit the postcode checker                     # features/step_definitions/coronavirus_local_restrictions_steps.rb:1
And I enter a valid postcode                          # …
```

Add test for Coronavirus local restriction checker

---

features/collections.feature

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Previously this app didn't have a healthcheck endpoint. This adds
a scenario to explicitly check the new endpoint [1] as a standard
safety check for apps that have Continuous Deployment enabled.
[1]: https://github.com/alphagov/collections/pull/1976
- Run …

Add healthcheck scenario for collections

---

features/coronavirus_local_restrictions.feature
features/step_definitions/coronavirus_local_restrictions_steps.rb

The postcode checker has been hidden to the public. This tests that the redirect to the appropriate guidance is in place.
- …

Add test for redirect from postcode checker to national guidance

---

features/authenticating_proxy.feature
features/draft_environment.feature

This updates Smokey to add further tests for Authenticating Proxy so we can enable CD for it. See individual commits for more details.
Related to https://github.com/alphagov/authenticating-proxy/pull/238 and here is an example build: https://deploy.blue.staging.govuk.digital/job/Smokey/7561/console

Authenticating proxy healthcheck

---

features/assets.feature

This was missed in https://github.com/alphagov/smokey/pull/740 and is another thing that we should test before safely deploying the app.

Tag draft assets with authenticating-proxy

---

features/authenticating_proxy.feature
features/collections.feature
features/finder_frontend.feature
features/government_frontend.feature
features/publisher.feature
features/publishing_api.feature
features/smartanswers.feature
features/travel_advice_publisher.feature

https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps
Previously in scenarios requesting the /healthcheck endpoint we only
verified the response code was 200, but this will always be the case
even if the app is unhealthy. This adjusts the /healthcheck scenarios
to actually verify the endpoint reports an "OK" status.
- Change the "Branch specifier" to the name of your …

Fix not actually checking app healthchecks

---

features/government_frontend.feature

The redirect for the register for self assessment option has been
changed in this PR: https://github.com/alphagov/publisher/pull/1376
This updates the value of the redirect in the smokey tests.
- Run …

Update the redirect to sign up for self assessment

---

features/finder_frontend.feature
features/foreign_travel_advice.feature

This has been changed in govuk_publishing_components.
See:
- https://deploy.integration.publishing.service.gov.uk/job/Smokey/25069/console
- https://www-origin.integration.publishing.service.gov.uk/search/news-and-communications
- https://www-origin.integration.publishing.service.gov.uk/foreign-travel-advice/turkey
- https://github.com/alphagov/govuk_publishing_components/commit/36953fd979db6c144ba0fd0245ed414066fc88b0

Change "Get email alerts" to "Get emails"

---

features/finder_frontend.feature

We currently have a problem with this test related to CORs and google
analytics so it is adding no value and blocking deployment. A fix is
needed but false fails are of no use to anybody so this turns of that specific test
for now.
Example fail: https://deploy.blue.production.govuk.digital/job/smokey/5990/console
- Run a new build of the …

Turn off broken test

---

features/content_data_api.feature

This PR adds a feature test for the content-data-api Healthcheck.
This is a pre-requisite for enabling continuous deployment for content-data-api.
Smokey test run: https://deploy.integration.publishing.service.gov.uk/job/Smokey/25167/console
(1 unrelated test failure)
Co-authored-by: Rebecca Pearce rebecca.pearce@digital.cabinet-office.gov.uk

Add Healthcheck feature test for content-data-api

---

features/finder_frontend.feature

Previously this test was disabled [1] over a month ago due to being
flakey. We believed that there was an issue with CORs and google
analytics which led to a card being created to investigate. Since then
I've tried re-enabling the test to replicate the flakeyness for
integration and staging which proved to be unsuccessful, as out of 30
runs, there were no failures. This commit re-enables the test as there
doesn't seem to be an issue anymore.
[1]: https://github.com/alphagov/smokey/pull/755
I've recorded all the builds as a comment on the [Trello card](https://trello.com/c/5hdexmoU/2292-investigate-fix-failing-smokey-test-for-finder-frontend-timebox-2-days).
the …

Re-enable malicious code test for finder-frontend

---

features/local_links_manager.feature
features/publishing_tools.feature

Added so continuous deployment can be enabled for
Local Links Manager.
Trello: https://trello.com/c/uAx6eKAQ/2276-activate-continuous-deployment-for-local-links-manager
- Run the [Smokey deploy job][] …

Add new healthcheck for Local Links Manager

---

config/cucumber.yml
features/frontend.feature
features/support/env.rb

This allows us to run smokey against the test AWS environment. The following test passes:
```
AUTH_USERNAME=x AUTH_PASSWORD=y ENVIRONMENT=test bundle exec cucumber --profile test --strict-undefined -t @replatforming -t "not @notreplatforming"
```
This is required by the replatforming team, as we're trying to get smokey running in & against ECS.

Add test environment

---

Dockerfile
Gemfile
Gemfile.lock
Rakefile
features/support/env.rb

This enables us to run the smoke tests from a container.
No build pipeline is set up for this yet. You'll need to manually build the container image with `docker build . -t smokey` then run the smoke tests like below.
Test environment (replatforming subset):
```
docker run -it -e AUTH_USERNAME=<user> -e AUTH_PASSWORD=<pass> -e ENVIRONMENT=test smokey bundle exec cucumber --profile test --strict-undefined -t 'not @benchmarking' -t @replatforming -t "not @notreplatforming"
```
Staging environment (smartanswers subset):
```
docker run -it -e AUTH_USERNAME=<user> -e AUTH_PASSWORD=<pass> -e ENVIRONMENT=staging_aws smokey bundle exec cucumber --profile staging_aws --strict-undefined -t 'not @benchmarking' -t @app-smartanswers
```
NB. Other environment variables are required (see [puppet for the …

Containerised smoke tests

---

features/licensing.feature

I want to be able to tell smokey to run just the tests that cover Licensing (🤢):
https://deploy.integration.publishing.service.gov.uk/job/Smokey/27314/console
At the moment I can't, because they don't have a tag.

Add tag to run licensing tests independently

---

features/info_frontend.feature

We've retired the GOV.UK registers, therefore info pages can no longer
display metrics. This removes that dependency in the Smokey test.

Refactor info frontend smokey tests

---

features/account_api.feature

This is to ensure that the app is running and can talk to postgres.
Based on https://github.com/alphagov/smokey/blob/main/features/travel_advice_publisher.feature
[Test run](https://deploy.integration.publishing.service.gov.uk/job/Smokey/27878/console)

Add a test for the account-api healthcheck

---

README.md

- Usage of `brew cask install` returns "Error: Calling brew cask install is disabled! Use brew install [--cask] instead." since Homebrew 2.6.0 (released in December).
:sparkling_heart:

README: Change `brew cask install` to plain `brew install`

---

features/frontend.feature
features/support/env.rb

Smokey currently doesn't have access to frontend in ECS, so marking this as `notreplatforming` will get tests passing against ECS again.
We'll probably remove this particular test once we have moved to ECS, since ECS or App Mesh will check the healthcheck endpoints directly.

Mark test as 'notreplatforming' so it won't run in ECS

---

features/publisher.feature
features/publishing_tools.feature
features/signon.feature

This will include the scenarios for Signon and Publisher in the set of smoke tests that are run against apps in ECS.
I've also added the tag app-signon to the signon suite so we can run those separately.

Add replatforming tag to Signon and Publisher scenarios

---

features/frontend.feature

We don't yet serve /robots.txt in ECS.
We also only serve 404 pages through Fastly, rather than
CloudFront, so I'm disabling this test until we've got
this set up.

Disable two frontend health checks in ECS

---

features/collections.feature

Taxon pages used to say "get emails about this topic", which was
inconsistent with topic pages, and that inconsistency has been
resolved.
---
Successful run: https://deploy.integration.publishing.service.gov.uk/job/Smokey/30286/console

Check for "get emails for this topic" on taxon pages

---

features/step_definitions/brexit_check_steps.rb

We're renaming /transition back to /brexit today.

Fix Brexit path

---

features/step_definitions/smokey_steps.rb

Smokey was failing with the release of the new gem_layout because this layout's homepage link in the header doesn't have the id `#logo`.
To fix this the selector has been changed to `.govuk-header__link` which is present in both `core_layout` and `gem_layout`.

Update header link CSS selector

---

config/cucumber.yml
features/waf.feature

We're now ignoring paths in the cache key for the
homepage. The WAF is behind Fastly so the requests
from this smoke test to the homepage won't actually
make it to the WAF.
The fix is to point the smoke test at another path.
Test it locally:
```
ENVIRONMENT=production_aws bundle exec cucumber \
--profile production_aws --strict-undefined features/waf.feature
```

Fix WAF smoke test

---

features/publisher.feature
features/step_definitions/publisher_steps.rb
features/step_definitions/smokey_steps.rb

This PR adds a smoke test for Publisher which creates a new draft `Place` and ensures it is then visible on the draft stack, before then proceeding to delete the draft.
This test will not run on existing production and will not run on the new replatformed production when it's ready, as it has been given the tag `@notproduction` (where the Smokey run for each environment by Concourse will exclude tags matching `@not<environment>`).
Trello: https://trello.com/c/9QipS0X0

Add publishing smoke test

---

features/publisher.feature

Smoke tests were recently added to test the end-to-end Publisher workflow - specifically creating, publishing and unpublishing content. In order to facilitate the publishing test, Smokey was granted the `skip_review` permission in integration and staging which then enables it to request 2i, skip review and publish immediately. Due to the daily Signon data sync from prod to staging however, manually added permissions do not persist in staging; as Smokey doesn't hold the `skip_review` permission in prod, this will also be the case in staging.
For now, the Replatforming team are deciding to only run this test in integration, where manually added permissions in Signon do persist as there is no daily Signon data sync that would otherwise overwrite this data. When we come to moving the new …

Only run Publisher publishing tests in integration

---

features/smartanswers.feature

The `pay-leave-for-parents` SmartAnswer was renamed to `maternity-paternity-pay-leave` in
https://github.com/alphagov/smart-answers/pull/4765
A redirect is in place so Smokey will continue to pass until this change is deployed.
[trello](https://trello.com/c/65jLhWvK/2019-to-deploy-16-june-update-questions-and-outcomes-in-pay-leave-for-parents-to-remove-shared-parental-leave-information)

Update SmartAnswer to new URL

---

features/account_api.feature
features/step_definitions/account_steps.rb
features/support/env.rb

We've had a few instances where the sign in journey has broken.  This
sort of thing is hard to catch when testing at the app level, as it
involves GOV.UK apps, an external auth service, and our CDN config.
We think that smoke tests which test the full journey from the
perspective of a user will help catch future breaking changes.
---
[Example successful Smokey run on integration](https://deploy.integration.publishing.service.gov.uk/job/Smokey/30935/console)
[Trello card](https://trello.com/c/a1mlNSkg/849-add-smoke-tests-for-signing-in-from-the-brexit-landing-page-the-checker-results-page)

Add tests for signing in to the GOV.UK account

---

features/support/env.rb

See also https://github.com/alphagov/govuk-puppet/pull/11157
[Successful smokey run on staging](https://deploy.blue.staging.govuk.digital/job/Smokey/12424/console)

Use separate env vars for account basic auth credentials

---

features/smartanswers.feature

The "check-landlord-immigration" smart answer is no longer suitable for testing Imminence, so this swaps it for one that is.
There is now only one SmartAnswer that uses Imminence, the BenefitCapCalculator.
This commit removes a Scenario for stepping through an Imminence-enabled smart answer because:
* the benefit cap calculator only uses a post-code in the final step
* it is possible for the steps to fail validation but to still return a 200,
making this test unreliable
Instead we can now rely on the existing "Check postcode lookup" Scenario which actually asserts that the Imminence call has succeeded by checking page text.
[trello](https://trello.com/c/4mogKZrw/2584-temporarily-take-down-check-if-someone-can-rent-your-residential-property-remove-the-start-page-button-replace-the-start-pag …

Change SmartAnswer example for Imminence test

---

features/feedback.feature
features/step_definitions/feedback_steps.rb
features/step_definitions/smokey_steps.rb

This adds regression tests for the feedback component that is available
across GOV.UK frontend apps. At the time of writing this
component is currently broken in a number of applications and we've
found out that there wasn't tests available to catch the problem. A fix
is currently in progress for the problem [1] and these are being added
so that we can learn sooner if the problem re-occurs.
The feedback component has become particularly complex as it requires a
high degree of integration. The items involved are: the frontend
application, the feedback application, the slimmer gem, static application
and it's integration with govuk_publishing_components. This seems to leave
Smokey as the only tool that has a sufficient perspective to test this
component is integrated correctly. Because of …

Feedback component tests for each frontend app

---

features/step_definitions/finder_frontend_steps.rb

In https://github.com/alphagov/govuk_publishing_components/pull/2211/files
the `gem-c-document-list__item-link` class was removed which led to this
test failing once v24.21.0 was released of the gem.
I've changed it to a class that remains that also doesn't risk the
ambiguity that led to a class being added in the first place [1].
However this seems rather fragile and could well break again in future.
I can't seem to find any better alternatives available or the ability
for finder-frontend to specify the selector.
[1]: https://github.com/alphagov/smokey/commit/93a07b6a6969357f79eaac7f36ea002317781e90

Change finder-frontend selector

---

features/smartanswers.feature

This calculator was removed in [an earlier PR](https://github.com/alphagov/smart-answers/pull/5527), so the related Smokey test can now be removed.
[Trello card](https://trello.com/c/OAnUbav7)

Remove Benefit Cap Calculator

---

features/data_gov_uk.feature

Stop CKAN alerts during upgrade to 2.9, this should be done after the redirection to CKAN maintenance started and worker processes stopped - https://github.com/alphagov/govuk-puppet/pull/11203
https://trello.com/c/DZJFi8z5/2613-create-prs-to-prep-for-29-upgrade
**You need to …

Stop CKAN alerts during upgrade to 2.9 (merge before upgrade started)

---

features/data_gov_uk.feature
features/step_definitions/datagovuk_steps.rb

Dataset count is in `h1` element not `h2`.
Error reported -
> expected to find css ".search-form h2" at least 1 time but there were no matches (Capybara::ExpectationNotMet)
./features/step_definitions/datagovuk_steps.rb:15:in `/^I save the dataset count$/'
**You need to manually …

Dataset count is now in h1 element not h2

---

features/feedback.feature

The [feedback component was removed](https://github.com/alphagov/feedback/commit/715aad1db1868a01774cc01f69c12e90bb4b1064#diff-f43fe075643e681b2c01c2f853bb0c4299d135b47fcbd4da96890d521c49e3eb) from the layout in the feedback app, so [this test won't ever pass](https://deploy.blue.production.govuk.digital/job/smokey/9044/console).
(You can check this on https://www.gov.uk/contact/govuk)

Fix Feedback test

---

features/authenticating_proxy.feature

This was making a request to the wrong app. Note that draft-origin
doesn't have a 'govuk-internal' DNS name, so we need to use the
public one. In future work we should consider giving the proxy its
own domain name so we can treat it consistently like other apps.
(We didn't need to previously because Varnish makes request directly
to its port on the same machine [1].)
[1]: https://github.com/alphagov/govuk-puppet/blob/32c1bbbb10067078c1406170666a135b4a10aaea/modules/govuk/manifests/node/s_cache.pp#L95
until you are confident your change …

Fix healthcheck for authenticating-proxy

---

features/account_api.feature

We're testing out the Digital Identity auth service in integration,
and we don't have a test user for that yet.
---
[Trello card](https://trello.com/c/ZvDGaba4/958-use-di-auth-in-integration-give-feedback-on-their-documentation)

Disable account-api login test in integration

---

features/support/account_dashboard.feature

To ensure any changes to menu headers on GOV.UK does not affect the sign-out links on GOV.UK Accounts.
[This build on Staging passed](https://deploy.blue.staging.govuk.digital/job/Smokey/14275/console) (DI are currently testing on integration so the [account related smoke tests will fail there](https://github.com/alphagov/smokey/pull/853)).
> The manual [Smokey job][] will pick up changes on `main` automatically. You only need to do a manual deployment for the [continuous Smokey loop][].
[Smokey job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey/
[continuous Smokey loop]: …

Add sign-out check

---

features/brexit_check.feature
features/step_definitions/brexit_check_steps.rb

We don't show those links any more, because we're retiring the checker at the end of this month.

Remove Brexit email signups smoke test

---

features/step_definitions/get_involved_page_steps.rb

An unused div was removed from the Get Involved page in https://github.com/alphagov/government-frontend/pull/2296 in order to fix the `And it should be populated` step of this test.
However this now causes the `When I click the next closing response link` step to fail, as the div is no longer present.
Updating the test to match the government-frontend changes.
- Change the "Branch specifier" to the …

Fix step in Get Involved test

---

features/frontend.feature

Should give us a clue if things break, as it's usually quite low traffic so might go unnoticed for a while.
Relevant: https://docs.publishing.service.gov.uk/apps/frontend/elections-api.html

Add smoke test for elections API

---

features/step_definitions/whitehall_steps.rb
features/whitehall.feature

A redesign of the homepage shipped and removed the ID. We should try to avoid adding IDs just for tests if possible.
[Proof that this ran against the `new-homepage` branch and passed](https://deploy.integration.publishing.service.gov.uk/job/Smokey/35864/console).
**You need to …

Fix test for homepage

---

features/data_gov_uk.feature

Disable smoke tests for CKAN during database upgrade
https://trello.com/c/lkdK9QM2/71-do-the-postgres-upgrade-for-ckan

Update data_gov_uk.feature to disable CKAN tests

---

features/data_gov_uk.feature

Enable CKAN smoke tests after upgrade complete.
https://trello.com/c/lkdK9QM2/71-do-the-postgres-upgrade-for-ckan

Update data_gov_uk feature to enable CKAN tests

---

features/benchmarking.feature
features/licensing.feature
features/search_api.feature

https://trello.com/c/D2Yt6TrG/251-audit-tests-in-the-smokey-repo
After this change we now have a more intuitive use of this marker:
it's now always used in combination with "@notstaging", indicating
the scenario only applies to Production (for whatever reason).
Examples of history for these markers:
- the PDF benchmarking scenario [1] used to fail [2] but works now
- the sitemap scenario [3] used to fail [4] but seems to work now
[1]: https://github.com/alphagov/smokey/blame/main/features/benchmarking.feature#L22
[2]: https://github.com/alphagov/smokey/commit/ec9030c05662d98d02f8b9e12e2c96440ee4bcbb
[3]: https://github.com/alphagov/smokey/blame/main/features/search_api.feature#L5
[4]: https://github.com/alphagov/smokey/commit/044d9f57b60580c2ded0238af9955308befe71c2
**You should manually …

Remove "@notintegration" where this is redundant

---

features/assets.feature
features/benchmarking.feature
features/draft_environment.feature
features/gov_uk.feature
features/licensing.feature
features/search_api.feature

https://trello.com/c/D2Yt6TrG/251-audit-tests-in-the-smokey-repo
This fixes several instances where we're not bypassing caching, and
yet I can see caching headers when manually requesting these pages.
Bypassing the cache means we can be confident that any changes to the
underlying frontends is picked up in a timely manner.
Scenarios that still don't bypass caching:
- "gov_uk_redirect.feature" - these are testing the CDN and I don't
observe any caching headers in the responses
- backend app features - cache bypass is not relevant to backend apps
- "mirror.feature" - I wasn't able to test this as I don't have access
to the Production mirrors
- draft environment authentication - these 302 responses appear to omit
caching headers (possibly an obscure Rails default)
- "ab_testing.feature", …

Bypass cache consistently for pages under test

---

features/assets.feature
features/collections.feature
features/contacts.feature
features/csv_preview.feature
features/feedback.feature
features/finder_frontend.feature
features/foreign_travel_advice.feature
features/gov_uk.feature
features/government_frontend.feature
features/info_frontend.feature
features/licence_finder.feature
features/licensing.feature
features/manuals_frontend.feature
features/public_api.feature
features/publisher.feature
features/router.feature
features/signon.feature
features/smartanswers.feature
features/whitehall.feature

These tests should pass now that the apps are running in Kubernetes (`replatforming` tag). I removed this tag from some apps which we're not going to be running in a passing state for the next milestone of our project.
I've also added in the `app-<appname>` tag to some apps which were missing it.

Enable tests for replatformed applications

---

features/frontend.feature
features/licensing.feature

- re-enable some smokey tests for frontend in EKS now that the frontend should be fulling working there.
- disable the test for licensify-admin in EKS since licensify is remaining in EC2 for now.

Re eable smokey tests

---

config/cucumber.yml
features/support/env.rb

https://github.com/alphagov/govuk-puppet/pull/11603
Follow-on from: [^1].
[^1]: https://github.com/alphagov/govuk-puppet/pull/11603
- Run the [Smokey deploy job][] to deploy the [continuous Smokey …

Remove redundant "_aws" environments

---

features/publishing_tools.feature

Collection publisher is being migrated over to Design system, the "Sign out" button has been changed to "Log out".
This change fixes the tests
- Run the [Smokey deploy job][] to deploy the [continuous …

Fix failing smokey tests on Collections Publisher

---

Dockerfile
README.md
features/step_definitions/smokey_steps.rb
features/support/env.rb
features/support/http_requests.rb

https://trello.com/c/DL5omRGP/230-smokey-needs-java-and-a-glitchy-proxy-server-to-run-tests
This isn't necessary since we switched to testing via the CDN [^1].
Integration Fastly doesn't require basic auth on the VPN [^2].
Tested and works with [the Smokey Jenkins job in Integration](https://deploy.integration.publishing.service.gov.uk/job/Smokey/39351/console) ✅.
Tested and works with Smokey Loop in Integration ✅.
Tested locally and works on VPN ✅.
Worth noting that gov_uk.feature doesn't pass locally even with basic 
auth - it requires a VPN connection.
[^1]: https://github.com/alphagov/smokey/commit/2c10c7541c98ebe450cd058813e0792954f4e5cf#diff-3c1d97c5f1fa7ca90a4a96df18478ce19fe4d3a8dbaa3914ccc6ec6c43e81cbeR18
[^2]: https://github.com/alphagov/govuk-cdn-config/blob/master/vcl_templates …

Remove redundant basic auth feature

---

README.md
features/support/env.rb
features/support/http_requests.rb

https://trello.com/c/DL5omRGP/230-smokey-needs-java-and-a-glitchy-proxy-server-to-run-tests
This is potentially unnecessary given many of the tests now probe
via the CDN, and the low frequency these run at in general means
it's highly unlikely it will trip any reasonable rate limiting at
our origin servers or our publishing backend servers.
Tested and works in Integration (Jenkins Job) ✅
Tested and works in Integration (Smokey Loop) ✅ 
There's still a risk that this will cause an issue in another environment 
over a sustained period, but I think it's worth the risk to merge and 
revert if we find this happens in practice.

Try removing rate limit bypass token everywhere

---

README.md

This repo isn't covered by GOV.UK Docker, which takes care of both
of these setup concerns. My quick attempt at adding it was partly
successful, but when running the tests the latter ~half fail e.g.
Then I should be able to visit:                 # features/step_definitions/smokey_steps.rb:162
| Path                           |
| /government/announcements.atom |
| /government/statistics.atom  |
invalid session id (Selenium::WebDriver::Error::InvalidSessionIdError)
For now it makes sense to at least offer guidance on running this repo
natively. Hopefully we can add it to GOV.UK Docker in future though.

Add guidance for installing Ruby / Chromedriver

---

README.md

Relates to: https://github.com/alphagov/govuk-docker/pull/597
This simplifies the setup required, with only a minor adjustment
needed to the command to run [^1]. In future we could also suggest
using dotenv to avoid putting credentials in commands. I've also
tweaked the headings so this repo consistent with other apps [^2].
To test locally:
- Pull the GOV.UK Docker changes
- Run "make smokey"
- Run the tests as described
[^1]: https://github.com/alphagov/govuk-docker/blob/main/docs/how-tos.md#how-to-set-environment-variables
[^2]: https://github.com/alphagov/content-publisher#technical-documentation

Use GOV.UK Docker for local development

---

features/support/hooks.rb

This is a relic from the gem we used to use [^1]. It doesn't work,
and fixing it just leads to duplicated output, which is what we got
with the old gem* but isn't something we need / want to keep - the
"raise" causes output on $stdout anyway, so there's no regression.
*Tested by going back to d46d928 and creating a fake JS error.
[^1]: https://github.com/alphagov/smokey/pull/933/files#diff-2f93a30bfa1ff6bdac9d65681869e6395ec22b89c7560730cbe195d77961673cL22

Remove redundant "puts" for async JS errors

---

Gemfile
Gemfile.lock
README.md
features/support/env.rb

Reinstates the rate limit header support, with web security turned off to avoid CORS errors.
When you make a cross origin request, there are certain headers you’re
allowed to send with it, in an allowlist. If you send any other header,
the system assumes you’re trying to authenticate yourself somehow or do
other dangerous cross-origin things. Our our rate-limit-header is treated
like that, so we'll get CORS errors. They're not important, so we just
turn off web security to remove them (before we filtered them out, as:
https://github.com/alphagov/smokey/pull/921)
Details about what --disable-web-security does: 
https://groups.google.com/a/chromium.org/g/chromium-discuss/c/Wms-ZaAwA1Q
https://github.com/chromium/chromium/blob/main/content/public/common/content_switches.cc#L280
Has been …

Fix cors problem reinstate rate limit support

---

features/search_api.feature
features/step_definitions/search_api_steps.rb

The sitemap is a critical feature of GOV.UK. However, we really,
_really_ don't need to check the whole thing to prove it works.
Before this change, the scenario would take ~40s to run, which is
about 25% of the total runtime of all Smokey tests - this was by
far the slowest test in the whole suite. Now it will only take ~3s
to run - a significant improvement.

Speed up sitemap test by only checking one link

---

features/assets.feature
features/caching.feature
features/collections.feature
features/content_data_admin.feature
features/csv_preview.feature
features/draft_environment.feature
features/feedback.feature
features/finder_frontend.feature
features/foreign_travel_advice.feature
features/frontend.feature
features/gov_uk.feature
features/government_frontend.feature
features/info_frontend.feature
features/licensing.feature
features/public_api.feature
features/search_api.feature
features/service_manual.feature
features/signon.feature
features/smartanswers.feature
features/transition.feature
features/whitehall.feature

https://trello.com/c/fRihmgQ8/266-add-top-level-guidance-about-where-we-write-tests-on-govuk
Another follow-up PR to #965. I've gone a bit further and looked at all the 
scenarios to see where the names could be better. Please see the commits 
for more details. After this we will have a minimal set of TODOs remaining 
and can move on to other work e.g. clarifying which files tests should be in.
If you're wondering about some of the claims of which app talks to which 
other app, [the original Smokey audit](https://docs.google.com/spreadsheets/d/1i2k4WexywoJurdFddOxiNICN-Elv1D5Mb2sdaCjF1t0/edit?disco=AAAASMdZEUQ) has links to supporting evidence for 
most of the tests ([example](https://docs.google.com/spreadsheets/d/1i2k4WexywoJurdFddOxiNICN-Elv1D5Mb2sdaCjF1t0/edit?disco=AAAASMdZEUQ)). …

Rename scenarios to be more consistent

---

features/assets.feature

This app is not involved in the scenario. Unlike documents, where
the request goes via Varnish to authenticating-proxy [^1], a request
for a draft asset goes directly to asset manager [^2].
It's possible for authenticating-proxy to be involved with requests
for draft assets, but that's a different scenario e.g. viewing an
image via a draft document with an auth bypass token [^3].
[^1]: https://github.com/alphagov/govuk-puppet/blob/fd12c90c7d0efe1328774a8c6dfd383594100959/modules/govuk/manifests/node/s_cache.pp#L94
[^2]: https://github.com/alphagov/govuk-puppet/blob/33c3adbfef8b7d9791ca846c2ac2871551e45ae4/modules/router/templates/draft-assets.conf.erb#L56
[^3]: https://github.com/alphagov/asset-manager/blob/1e88cd5b71b8ac6f73a079176b9f74c57b608d1c/app/controllers/media_controller.rb#L71

Remove incorrect authenticating-proxy tag

---

features/assets.feature
features/step_definitions/draft_environment_steps.rb

Previously we would try to view a non-existent asset, which didn't
matter as we were only checking the redirect to Signon, which works
irrespective of the asset existing [^1].
Now we test the full journey of viewing a draft asset*. I've chosen
to use an image because this will preview in the headless browser,
which is easier to check and avoids an actual download.
*Note: the asset is published but, like published documents, also
exists in draft as well.
Tested and works on [Integration Jenkins](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40521/console) ✅.
[^1]: https://github.com/alphagov/asset-manager/blob/1e88cd5b71b8ac6f73a079176b9f74c57b608d1c/app/controllers/media_controller.rb#L54

Improve test for visiting a draft asset

---

features/apps/whitehall.feature

As part of enabling CD for asset manager, this PR tags a few Whitehall tests that interact with asset manager so that we can ensure they are run as part of asset manager's deploy.
Tested on integration: https://deploy.integration.publishing.service.gov.uk/job/Smokey/40649/
(currently failing for unrelated reasons that can be seen on other earlier builds)
Trello: https://trello.com/c/Sj4UTatV/126-enable-continuous-deployment-for-asset-manager

Tag asset manager in relevant whitehall tests

---

features/apps/collections.feature
features/apps/finder_frontend.feature
features/apps/government_frontend.feature

These scenarios cover part of the app by loading the page where we
ask how often a user wants to receive emails.
The Collections scenario also covers a legacy type of page rendered
by Email Alert Frontend [^1].
Tested and works on [Integration Jenkins](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40690/console) ✅.
[^1]: https://github.com/alphagov/email-alert-frontend#signup

Add missing tags for Email Alert Frontend

---

features/apps/feedback.feature
features/step_definitions/feedback_steps.rb

This can be removed now that the feature has been imported into Feedback
[1].
Note: I'm not able to remove the step definition for "I see the code
returned in the page" as this is still used by finder-frontend [2].
However once this PR is merged I should be able to add that onto [3].
[1]: https://github.com/alphagov/feedback/pull/1454
[2]: https://github.com/alphagov/smokey/blob/7553a432259d785fb6d4fb81cfd4fe3572185ad3/features/apps/finder_frontend.feature#L77
[3]: https://github.com/alphagov/smokey/pull/990

Remove Feedback export feature and corresponding steps

---

features/apps/signon.feature
features/step_definitions/cookie_steps.rb

This test is being removed because it doesn't meet the eligibility
criteria for this repository.
I investigated whether it could be imported to signon, but this is not a
simple task as the "secure" property is defined by the environment the
code is executing in [1].
With this knowledge I decided we could delete this for a few reasons:
1) It's unconventional for us to test convention in this way
2) The risks of this cookie not being secure are very low due to HSTS
making it very difficult to visit the site without HTTPS
3) There are various cookie tests in signon, which make the likelihood
of a regression low
If we were to want to test this Smokey could be the place if we were to
define an eligibility criteria of environment configuration. As this
test seems to be the lone case of this …

Remove signon secure cookie test

---

features/apps/finder_frontend.feature
features/step_definitions/feedback_steps.rb
features/step_definitions/smokey_steps.rb

This depends on https://github.com/alphagov/finder-frontend/pull/2815
These tests have been imported to Finder Frontend as they test code
local to that app and don't require the external view Smokey has.

Remove finder frontend export features and corresponding steps

---

features/apps/static.feature

[Trello card](https://trello.com/c/XDLC291t/2948-write-test-for-static-to-go-hand-in-hand-with-smokey-3)
This depends on another PR in Static[^1], which must be merged first.
This test has been reproduced in Static itself, but should be preserved here as a critical second check that the Static and Slimmer codebases can correctly integrate.
[^1]: https://github.com/alphagov/static/pull/2835

Remove TODO from Static feature test

---

features/step_definitions/frontend_steps.rb

We are removing the Miller Column style template for gov.uk/browse and replacing it with a new template. The markup for this smoke test is changed.
[Trello](https://trello.com/c/RDZA1vJ7/1109-build-iteration-of-level-2-browse-curated-topic-template-b-c-test-xl)

Fix Collections steps

---

.github/workflows/deploy.yaml

This removes the workflowTrigger parameter from the deploy workflow, which is no longer used. This should fix the call to the reusable workflow.

Remove extra parameter in deploy workflow

---

features/apps/content_store.feature

Added application tagging to the content store healthcheck, in line with
CD requirements.
Trello: https://trello.com/c/aDiHro0u/26-enable-continuous-deployment-for-content-store

Added application tagging to the content store healthcheck

---

features/apps/government_frontend.feature
features/apps/publisher.feature
features/apps/whitehall.feature
features/assets.feature
features/origin.feature

The EKS platform is currently only running the frontend applications and serving traffic to frontend application. Smokey needs to ignore scenarios that involve user journeys other than request public frontend pages (i.e. not publishing).

Add `notreplatforming` tag to irrelevant scenarios

---

features/apps/whitehall.feature
features/step_definitions/smokey_steps.rb

When we are in Reshuffle Mode, the Ministers page has different content and the smoke test for it fails.

Add spec to handle Reshuffle Mode

---

.github/workflows/ci.yaml
features/apps/smokey.feature
features/support/env.rb

[Trello card](https://trello.com/c/FPbuquwu/2953-investigate-setting-up-ci-for-smokey-5)
This adds a quick ~sanity~ sense check when a branch is pushed or a PR is raised to ensure that Smokey isn't fundamentally broken (which can happen when e.g. Dependabot PR with incompatible changes is merged[^1]).
This has been tested on a separate branch to ensure that the test fails when the broken change from the PR above is merged[^2].
I still have some open questions about this PR, could the reviewer please let me know what they think:
- I'm not sure what name the workflow and job should have. Is "CI" appropriate? Maybe "~Sanity~ Sense check" would be more appropriate? Or something else?
- The test only fails for the above-mentioned Dependabot PR when the `RATE_LIMIT_TOKEN` environment variable …

Add continuous integration for Smokey itself

---

features/step_definitions/feedback_steps.rb

In a recent change to the site wide feedback form, the text for the close button was changed from 'Close' to 'Cancel'. This resulted in "I close the open feedback form" to fail because it was clicking on a button with "Close" text. The label of this button has been updated in the test, so the button can now be found.
[Link to change in PR](https://github.com/alphagov/govuk_publishing_components/pull/2894/commits/595432dc2739523c026d25786a6c6ae3ad1c3152)
[Trello Card for Original Task](https://trello.com/c/kHCz2XVL/1046-iterate-and-implement-the-design-update-to-the-feedback-component-l)

Change feedback close button text to cancel

---

Dockerfile
Gemfile.lock
features/apps/smokey.feature
features/step_definitions/smokey_steps.rb
features/support/env.rb
features/support/http_requests.rb

This PR drops Chromium/ChromiumDriver in favour of Chrome, which we'd successfully used in publishing-e2e-tests prior to its retirement. It modernises some of the configuration, and adds a test to ensure that "rate limit token" request header setting works correctly.
It has been tested on Integration and had a successful run: https://deploy.integration.publishing.service.gov.uk/job/Smokey/43515/console (after configuring the job to use the `fix-build` branch rather than `main`).
See commits for details. TLDR, this PR fixes the build issues that we'd started seeing on every PR in Smokey.

Switch to Chrome to fix CI

---

Dockerfile
Gemfile.lock

- Don't try to run `rake webdrivers:chromedriver:update`, since that task and indeed the entire Rakefile were removed in https://github.com/alphagov/smokey/pull/893. Fixes the image build, which had been broken since https://github.com/alphagov/smokey/pull/1049.
- Actually install ChromeDriver, which had been missing since https://github.com/alphagov/smokey/pull/1049.
Other fixes and cleanup while we're there:
- Security fix: don't run as root by default.
- Security fix: don't defeat the Chrome sandbox by default.
- Use govuk-ruby-images, which gets rid of a ton of bad-practice `apt-get upgrade` and the like.
- Remove the JRE, as this was only needed for BrowserMob, which we're no longer using.
- Stop using deprecated `apt-key`.
- Update Bundler from 2.1 to 2.3, since 2.1 had some issues …

Fix container image build.

---

features/support/env.rb

This allows running the WebDriver tests in a container without needing to tune sysctls on the node and reserve a ton of RAM.
Also disable GPU acceleration and the ability to load Chrome extensions while we're at it, since we don't need/want either of those.

Have headless Chrome use /tmp instead of shared memory.

---

Dockerfile

This is no longer necessary now that we're setting `XDG_DATA_HOME` in the base image.
This doesn't affect the EC2/Jenkins setup.
Tested: deployed to integration, got identical test results as the trunk build.

Remove workaround for Chrome writing to `~/.local`.

---

features/support/env.rb

- Stop accepting insecure TLS certs by default. Integration, staging and prod have valid certs.
- Add a couple of env vars to allow enabling ChromeDriver verbose logging (disabled by default).
Tested: [ran the full suite from branch](https://deploy.integration.publishing.service.gov.uk/job/Smokey/44287/console).

Validate TLS certs by default and add a flag for ChromeDriver logging.

---

features/apps/frontend.feature
features/cdn.feature

This updates the postcode used in two frontend tests to WC2B 6NH, because we now have split postcode support and the previous postcode was a split one, complicating the output to test against (there's no big advantage from the point of view of the smokey test to making it use the old postcode and updating the checked output, so we just change to a non-split postcode).
**You should manually test your PR before merging.** (DONE)
Run in integration against this branch: https://deploy.integration.publishing.service.gov.uk/job/Smokey/46012/console

Update postcode in frontend calls to avoid split-postcode page

---

features/step_definitions/analytics.rb

According to the [Google Analytics documentation][1], events are tracked by calling the endpoint `https://www.google-analytics.com/j/collect`
To track a 'pageview' event, the request must include either the `dl` parameter, or both the `dh` and `dp` parameters.
For example, a page view of `http://example.com/foobar` could be tracked with either of the following:
- `dl=http%3A%2F%2Fexample.com%2Ffoobar`
- `dh=example.com&dp=%2Ffoobar`
Our Smokey test was trying to assert that a pageview event had been tracked for the search page by looking for the `dp` parameter:
```
dp=%2Fsearch%2Fall%3Fkeywords%3Dexample
```
However, something seems to have changed in the way Google Analytics is tracking these page views. Instead of submitting the `dh` + `dp` parameters, it now seems to be using the `dl` …

Make Google Analytics assertion less brittle

---

features/step_definitions/whitehall_steps.rb

The "Check whitehall assets are redirected to and served from the asset host" scenario can't pass on the Replatforming clusters (before going live) otherwise.

Fix assertion about the assets domain name.

---

Dockerfile

Chromedriver seems to be having a problem since we switched the base image to jemalloc. Let's see if it's causal.
This only affects the k8s environments.

Use the default allocator instead of jemalloc.

---

features/support/hooks.rb

The addition of a 'hint' to the Sentry event causes the SDK to fail when sending the event.
This should fix https://github.com/alphagov/smokey/issues/1080
https://trello.com/c/asECCyWk/3096-fix-smokey-sentry-integration-3

Remove hint from Sentry event

---

features/apps/sidekiq_monitoring.feature
features/step_definitions/sidekiq_monitoring_steps.rb

These ensure we are able to load the dashboard for the sidekiq monitoring of each application where it is used.
This has been tested in https://deploy.integration.publishing.service.gov.uk/job/Smokey/49158/console.
[Trello card](https://trello.com/c/aVx282Rt)

Add tests for sidekiq-monitoring

---

features/apps/sidekiq_monitoring.feature

We're not running the [sidekiq-monitoring dashboard app](https://github.com/alphagov/sidekiq-monitoring) in k8s.
Test run passed on the integration cluster.

Don't probe sidekiq dashboard app on k8s.

---

features/origin.feature
features/step_definitions/draft_environment_steps.rb

The `Check visiting a draft page requires a signon session` scenario contained the step `When I attempt to go to a case study`, which was unhelpful because it didn't say what page it was actually requesting.
It was also a redundant step definition, as it was just a special case of the `when I visit` step.
<details><summary>Output when succeeding</summary>
```
@app-authenticating-proxy
Scenario: Check visiting a draft page requires a signon session                                       # features/origin.feature:29
Given I am testing "draft-origin"                                                                   # features/step_definitions/smokey_steps.rb:3
application_external_url(draft-origin) = 'https://draft-origin.eks.integration.govuk.digital'
When I attempt to visit …
```

Fix an opaque step name.

---

docs/deployment.md

We will soon be [removing Smokey from Jenkins](https://trello.com/c/ahTC4Wjj/3134-disable-smokey-in-jenkins-2) entirely (as it only tests the EC2 versions of apps, which no longer serve traffic). We therefore need to update our processes for testing Dependabot PRs.

Update manual test instructions for EKS

---

features/apps/frontend.feature
features/apps/whitehall.feature

CSV Previews are now rendered by Frontend, instead of Asset Manager, so we need to test that application instead.
Depends on https://github.com/alphagov/govuk-helm-charts/pull/1186.
[Trello card](https://trello.com/c/1kmt0VHe)

Move CSV Preview test from Whitehall to Frontend

---

features/apps/frontend.feature
features/apps/licence_finder.feature

Licence Finder is being retired, and licence URLs are going to update (although redirects will be in place for them).
- Remove licence finder test (it no longer exists)
- Update URL in frontend test to check it can talk to licensing so that it doesn't go through the redirect.
https://trello.com/c/VWSPy1u4/2055-create-pr-updating-smokey-test
Has been tested locally against integration - the updated test as expected fails when the new licence finder licence urls are not present, but passes when the licence data import task has been run.

Update/Remove licence-finder tests

---

Dockerfile

Chromedriver distribution has changed - the base URL for chromedriver packages has been updated, and the files that are downloaded have changed structure. They now include an internal directory, and the order is licence file first, then chromedriver. 
This means we can't use funzip, since that will only unzip the first file in a zip file. Unzip will handle it more gracefully, but can't take an input from stdin. So we download the file to /tmp, unzip the chromedriver from it, move it to the correct directory, then delete the tmp zipfile.

Chromedriver 115 fix

---

features/apps/frontend.feature

We disabled the busking-licence test as there was datasync issues, however this seems to be resolved now so we can reapply the test in integration.
https://www.integration.publishing.service.gov.uk/find-licences/busking-licence

Reapply licence smoke test in integration

---

features/apps/manuals_publisher.feature

The text for the sign out link in the manuals publisher header has changed from "Sign out" to "Log out" as part of the transition to using the GDS design system. Update the smokey test to expect the new text.

Update manuals publisher test following update to MP

---

features/support/base_urls.rb

https://trello.com/c/1VXQW5I1/2127-epic-retire-original-licence-finder-application

Remove licence finder from base paths now it's retired.

---

features/step_definitions/finder_frontend_steps.rb

Updating this for the same reason a test was recently updated in a [Finder Frontend PR](https://github.com/alphagov/finder-frontend/commit/f49a2d9c6544f866461b83c805e697efb2e41e70) 'Document list structure recently changed, __item-title is no longer the link but contains the link'.
This is in response to a [smoke test failure](https://argo-workflows.eks.production.govuk.digital/workflows/apps/finder-frontend-post-sync-j8qmp[…]-sync-j8qmp-3226574498&nodePanelView=containers) which was blocking deploys to staging and prod. 

Update structure of selecting element for clicking on a result

---

features/apps/collections_publisher.feature
features/apps/contacts_admin.feature
features/apps/content_data_admin.feature
features/apps/content_publisher.feature
features/apps/content_tagger.feature
features/apps/imminence.feature
features/apps/local_links_manager.feature
features/apps/manuals_publisher.feature
features/apps/maslow.feature
features/apps/publisher.feature
features/apps/service_manual_publisher.feature
features/apps/short_url_manager.feature
features/apps/specialist_publisher.feature
features/apps/travel_advice_publisher.feature

These end-to-end tests contained unnecessary [change detectors](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html), which are of negative value because they break unexpectedly for reasons unrelated to the behaviours that they're trying to test.
These tests are all meant simply to assert that a user was able to see the logged-in front page of each app. One of them recently broke because the string "Sign out" was changed to "Log out".
Tested: no new test failures in integration.

Remove unhelpful assertions from smoke tests.

---

README.md

Fix missing `base64 -d` from example commands for fetching the smoke-test Signon account creds from the cluster.

Fix example commands in README.

---

features/apps/whitehall.feature

Whitehall Frontend has been switched off, so we do not need to run tests against it.
[Trello card](https://trello.com/c/EXYnAQlT)

Remove remaining Whitehall Frontend test

---

Dockerfile

This is the recommended approach for chromedriver versions 115 and onwards[^1], which are no longer available via the old route (therefore rendering our build script broken).
I have removed the version matching between chrome and chromedriver, because there is currently a version mismatch (the corresponding chromedriver for the current version of chrome isn't available yet). However, because we install the latest stable release of each, they _should_ be compatible with each other in most cases.
It _should_ be possible to install Chrome itself with the same npx script, but the script does not automatically install Chrome's dependencies (unlike the Ubuntu package that we currently use), so this would require other changes to our build script.
This is live in integration right now, and …

Use @puppeteer/browsers to install chromedriver

---

features/step_definitions/finder_frontend_steps.rb

We don't have `a` tags nested in each other. This means the test can't find the search result to click on.
The search result markup looks like this (trimmed for brevity):
```
<div class="gem-c-document-list__item-title">
<a class="  govuk-link" href="/pay-dartford-crossing-charge">Pay the Dartford Crossing charge (Dart Charge)</a>
</div>
```
so removing the first `a`, should fix things.

Update search result selector

---

features/apps/frontend.feature

Frontend currently renders csv previews using `/government/uploads` path and `/media/:id/:filename` path.
This PR reverts the temporary commit to remove test for `/government/uploads` path and test for `/media/:id/:filename` path.
[Trello](https://trello.com/c/yDmtjPXG/199-task-frontend-smokey-tests-to-test-csv-preview-dependencies)

Add test for media path

---

features/support/env.rb
features/support/http_requests.rb

Adds a comment about how the user agent is now being used by GA4.
So that devs are aware if they want to change the value.

Add comment about GA4 to user-agent lines

---

features/support/env.rb

Within the cucumber tests, fetching logs from the driver is broken with the new chrome version 119 -> 120 upgrade. This issue seems to be solved in this github issue thread by updating the options to '--headless=new' SeleniumHQ/selenium#13112
This is from the [same issue in another repo](https://github.com/alphagov/govuk_test/pull/68)

Update options so the new chrome driver version 120 will work

---

features/apps/frontend.feature

Legacy preview endpoint for frontend is already removed, so we can remove the test as well.
[Trello card](https://trello.com/c/Kp9nquOr/71-task-remove-whitehallasset-concept-from-asset-manager-and-gds-api-adapters)

Remove legacy CSV preview test from frontend

---

features/apps/finder_frontend.feature
features/step_definitions/analytics.rb

The three search queries used in these smokey tests are inflating and polluting the clickboost search data.
The GA4/Analytics team tried to filter out the Smokey data at the GA4 end but weren't fully able to.
The test can be removed for a few reasons:
1. The clickboost data is being used to evaluate the new search product and that can't happen effectively if the clickboost data thinks pages are popular based on clicks occurring in tests. Once the new product is live it will continue to effect the results that users see.
2. search-analytics hasn't worked properly since the move to kubernetes, though work is being done to retify this.
3. These tests check for Univeral Analytics which is being removed, so the tests will need to br written anyhow.
**You should manually test your PR before …

Remove the search-analytics smokey tests

---

features/step_definitions/feedback_steps.rb

Form actions can contain a domain name, but `feedback_steps.rb` does 
not take it into account and it assumes the action URL can only contain a path but not a domain. This PR fixes that by checking if the action url **ends with** (as opposed to be equal to) the path.
This is a proposed PR fixing an ongoing bug with the smokey test. It does not introduce new any functionalities. For this reason it does not contain the ticket reference.

Fix static feature

---

README.md
features/support/env.rb
features/support/govuk_proxy_profiles.rb

- Cucumber now calls `govuk_proxy_runner.rb` when the proxy is required for the tests.
- README has been updated accordingly.
- Also fixes some misconfigurations for the govuk proxy profiles
See commits for details.
Makes it easier to run the proxy tests. Depended on by https://github.com/alphagov/govuk-helm-charts/pull/1774
Trello: https://trello.com/c/2XwAz6JD/3365-run-automatic-smokey-tests-against-the-standby-cdn-5

Automatically spin up proxy when running proxy-based Smokey tests

---

features/licensing.feature

It fails to load the favicon, which doesn't impact on user experience.

Ignore javascript errors for licensify

---

features/cdn.feature

The happy path for getting a /find-local-council result is:
1. --> `POST` postcode (eg "E1 8QS") to /find-local-council
2. <-- 302 redirect to the page for the council(s) (eg "/find-local-council/tower-hamlets")
3. --> `GET` /find-local-council/tower-hamlets
4. <-- 200 response containing the council details
The current test disables following redirects, so that we can examine the cache headers for the response. This means we never get to step 3 (which is fine because we're just checking that the CDN isn't caching stuff)
The last step then tries to check for content on a page that only exists if you _do_ follow the redirect (that is, render the page at step 4). I'm not sure how this would work.
Instead, we'll just check that we get the 302 response that is received at step 2. This shows …

Fix local council CDN test

---

features/apps/publisher.feature
features/step_definitions/publisher_steps.rb
features/step_definitions/smokey_steps.rb

Add a test that will attempt to create an artefact in Mainstream Publisher and then delete it.
If this test fails it will mean that the artefact created will need manual deletion before the Smokey test can pass again, but this is deemed acceptable by the team as it should be a rare occurrence.
We will run this test in integration and staging, but NOT production, to avoid adding junk data into the production database (and the data in integration and staging is overwritten overnight).
The latest version of the mongo driver currently causes the app to fail in deployed environments when saving to the database. This issue does not occur locally, and so we have no way of testing the driver update is safe without manual deployment and testing.
While having a Smokey test is not ideal, since it …

Add a Mainstream Publisher non-production test

---

features/licensing.feature

This renames the test label for licensify so that they are correct referenced in the post sync workflow, which expected them to match the ArgoCD App name.

Rename licensify tests

---

features/cdn.feature

Check HSTS header is present in 404 pages.
Related to PR: https://github.com/alphagov/govuk-fastly/pull/62
Tested branch shown here https://argo.eks.integration.govuk.digital/applications/smokey?orphaned=false&resource=&node=batch%2FJob%2Fapps%2Fsmokey-28477000%2F0
Trello: https://trello.com/c/0TgCOgbX/3397-3-configure-fastly-to-always-append-an-hsts-header

Test HSTS header for 404 status codes

---

features/step_definitions/smokey_steps.rb

Reverts alphagov/smokey#1279
Not needed now that Imminence has moved through the stack.

Revert "Add special case for imminence landing page"

---

features/apps/feedback.feature
features/apps/static.feature
features/step_definitions/feedback_steps.rb

Recent changes to the `govuk_publishing_components` removed the ability to input an email address in the feedback form, linking instead straight to the smart survey. These changes were intentional.
Removing the references to the form from the feature and steps.

Remove references to feedback form from feature tests

---

features/support/env.rb

This is attempting to work around the apparent Selenium Manager issues - we're explicitly specifying the path of the `chromedriver` executable path.
If we continue to get odd results, we can build Selenium Manager ourselves [as suggested by the community](https://github.com/SeleniumHQ/selenium/issues/12651#issuecomment-1734785707).

Workaround Selenium Manager issues

---

features/apps/government_frontend.feature

- Summary hasn't been available on these pages since 17/08/2023, replacing with Warnings and insurance
Confirmed this removes the government-frontend travel advice error in Smokey in integration.

Update foreign-travel-advice test to look for correct text

---

features/apps/frontend.feature
features/step_definitions/ab_testing_steps.rb
features/step_definitions/analytics.rb
features/support/browser.rb

These tests don't work without UA - there are no GA4 tests replacing them, so we can just remove them.

Remove analytics tests which are not appropriate for the GA4 world

---

features/cdn.feature

Since #1310, `cdn.feature` has been failing with:
```
Undefined Scenarios:
cucumber -p production features/cdn.feature:9 # Scenario: Check an A/B test is persistent
...
You can implement step definitions for undefined steps with these snippets:
Then('the bucket is reported to Google Analytics') do
...
```

Remove dangling reference to a deleted Analytics step.

---

features/step_definitions/click_button_steps.rb

Fix failing tests with radio and checkbox inputs
Version 5.1.0 of govuk-frontend contains refactoring to the CSS for radio buttons and checkboxes, this change resulted in tests throwing an `ElementClickInterceptedError`.
This was logged as a GitHub issue in govuk-frontend
- https://github.com/alphagov/govuk-frontend/issues/4762
This issue was fixed in version 5.2.0 - https://github.com/alphagov/govuk-frontend/pull/4768

Fix failing checkbox test in click_button_steps

---

features/apps/govuk_chat.feature
features/step_definitions/govuk_chat_steps.rb

https://trello.com/c/bnG6AjtP/1937
Adds two simple tests:
1. For a non-signed in user viewing a static page. We use the about page here instead of the homepage as the Chat app can be turned on and off to allow and disallow public access while it's still in beta mode. So the homepage can change state, which is why we test against a static page that won't change.
2. For a signed-in user viewing the admin area
Chat is set up slightly differently on integration/staging vs prod currently. Chat is still in beta so it's only available via the external URL on prod.  So a custom step definition was needed here to set the external URL differently on integration. Once we've got all environments consistent, we can delete this whole step definition file and just use the existing "When I visit x" …

Add tests for GOV.UK Chat

---

features/step_definitions/govuk_chat_steps.rb

Using `application_internal_url("chat")` returns a url of "https://chat". Instead we want the actual full URL of "https://www.integration.publishing.service.gov.uk"

Fix internal URL for GOV.UK Chat test

---

features/assets.feature

[Trello](https://trello.com/c/hrekcXsz/1414-fix-asset-manager-smokey-test)
We're seeing the following error in the "Check a draft asset can be served" scenario
```
Detected JS errors:
https://draft-assets.integration.publishing.service.gov.uk/favicon.ico - Failed to load resource: the server responded with a status of 404 () (RuntimeError)
./features/support/hooks.rb:31:in `After'
```
Given this is effectively testing Asset Manager's use as an API, we think we can safely ignore JavaScript errors in these scenarios
This scenario seemed to start failing after this favicon-related change in Static: https://github.com/alphagov/static/pull/3443

Fix Asset Manager errors
