alphagov/smokey

features/performance_platform.feature
The Performance Platform homepage has changed. Update the test to reflect that.
=> Update Performance Platform homepage test

features/smartanswers.feature
- /calcuate-your-maternity-pay was deleted and redirected.
=> Check the existence of /pay-leave-for-parents

features/gov_uk.feature
This behaviour is implemented in our Varnish VCL and is not currently tested anywhere.
https://github.gds/gds/puppet/blob/06b39b70339/modules/varnish/templates/default.vcl.erb#L31-37
=> Add test for trailing slash behaviour

features/government_frontend.feature
There wasn't one. There is now.
=> Add a smoke test for government-frontend

features/step_definitions/email_campaign_steps.rb
Still had a test URL in there.
=> Fix email-campaign feature.

features/licencefinder.feature, features/licensing.feature
Somehow in 083eee952eddd690a486e4c8ceb71476860735ee I changed the completely wrong thing. I've no idea how I survive in this job sometimes.
=> Bugfix wrong Smokey update

tests_json_output.sh
I renamed this file but missed the usage.
=> Fix usage in tests_json_output.sh

features/performance_platform.feature
These have been broken for a while in integration.
=> Add tests for Performance Platform

features/support/base_urls.rb
This is needed for the test added in 05394a7d081a2ae759c9215aef0d3baf2300b79e.
=> Add local-links-manager base URL

features/finder_frontend.feature
Finding Things team has migrated this page to a finder. This commit makes sure it gets tested trough smokey.
Can be merged once https://trello.com/c/8n6xIb5h is deployed.
=> Add statistical data set page

features/finder_frontend.feature
This has been failing:
https://deploy.staging.publishing.service.gov.uk/job/Smokey/4665/consoleFull
=> Fix test on HMRC finder page

features/whitehall.feature
Replace with appropriate alternative.
=> Remove reference to Dai Vaughan

features/frontend.feature, features/step_definitions/smokey_steps.rb
This will need revisiting once issues with the Frontend release are resolved.
This reverts commit 9203b2e5977bd74718b6f320d5a1396d9bf97330.
=> Revert "Fix place postcode request test"

features/mainstream_publishing_tools.feature, features/support/base_urls.rb
https://trello.com/c/dGPNmVub/482-retire-panopticon
=> Remove Panopticon-related steps

config/cucumber.yml, features/collections.feature, features/step_definitions/ab_testing_steps.rb, features/step_definitions/collections_steps.rb
Checks basic behaviour of the`collections` accordion component. Most of the coverage is provided by Jasmine, and this test is here as a sense-check.
https://trello.com/c/4UA30r0F/408-add-javascript-tests-in-collections-to-test-the-behaviour-of-the-accordion
=> Test collections accordion

features/mirror.feature, features/step_definitions/mirror_steps.rb
Mirror provider 0 is being decommissioned, only test with provider 1
=> Remove mirror provider 0 from tests

features/smartanswers.feature
Trello https://trello.com/c/0RTrCjIU/644-extend-smokey-tests-on-smart-answers
=> Improve smart answers feature

features/smartanswers.feature
This seems to cause issues with authentication.
=> Remove without following redirects from smartanswers

features/step_definitions/draft_environment_steps.rb
To one that does not have JavaScript from YouTube on the page, as this
errors when tested by Smokey.
=> Switch the case study used for the draft environment tests

features/mirror.feature
Add back in test that relate to smokey mirrors that were broken.
Reverts https://github.com/alphagov/smokey/pull/305
https://trello.com/c/nvWkhcLU/393-revert-smokey-mirror-test-removal
=> Revert "Remove some mirror features"

features/search.feature
This test is failing a lot on integration.
Work is planned to fix it in https://trello.com/c/DmzPTudf
=> Disable Smokey sitemap testing on integration

features/government_frontend.feature
We have recently updated the content on the page that we use to feature test
service sign in pages (see https://github.com/alphagov/publisher/pull/726), so we update the tests to reflect these changes.
=> Update Service Sign In feature tests

features/step_definitions/search_steps.rb
This is now using the option list component
This was causing failures in smokey
=> Update selector for organisation count in search results

features/step_definitions/finder_frontend_steps.rb
Option select component is now in finder-frontend:
https://github.com/alphagov/finder-frontend/pull/381
=> Switch finder test to app component

features/step_definitions/smokey_steps.rb
Add a $ at the end to separate this from the I am testing "..."
internally step.
=> Fix the ambiguity of the I am testing step

features/info_frontend.feature
Request a page served by info-frontend and look for some strings.
[Trello card](https://trello.com/c/ikOjBdox/92-add-missing-smokey-tests-for-frontend-apps-2)
=> Add a test for the benefits info page

features/feedback.feature
Hit /contact/govuk and check the page renders.
---
[Trello card](https://trello.com/c/ikOjBdox/92-add-missing-smokey-tests-for-frontend-apps-2)
=> Check that the contact form renders

features/collections.feature, features/government_frontend.feature, features/whitehall.feature
https://trello.com/c/XRXhTtxe/91-improve-smokey-tests-for-frontend-apps-2
Adds additional coverage for Whitehall and Collections.
=> Improve frontend tests

features/smartanswers.feature
This changed in https://github.com/alphagov/smart-answers/pull/3553
=> Remove check for Venezuela consulate email address

features/feedback.feature, features/finder_frontend.feature, features/search.feature, features/step_definitions/feedback_steps.rb, features/step_definitions/finder_frontend_steps.rb
This PR is for three smokey tests. It tests a basic XSS attack against the following:
- search
- feedback
- finder
=> Test for input sanitisation

features/collections.feature, features/services_information.feature
These pages are served by collections and so should be tested together with other collections tests.
=> Move services and information tests to collections

features/government_frontend.feature
These are timing out and were previously marked as `@pending` so re-mark them pending investigation.
=> Mark Government Gateway tests as pending

features/whitehall.feature
The Rt Hon Sir Eric Pickles is now The Rt Hon The Lord (Eric) Pickles.
=> Update name for people page check

features/draft_environment.feature
The page design has changed, as this content is now tagged to a Topic
page in the "live" phase. Update the expected text to match some text
on the page.
=> Fix one draft environment test

features/support/env.rb
https://trello.com/c/ftCfaDhf/452-investigate-frequent-smokey-youtube-error
These didn't have the desired effect so reverting to previous config.
=> Revert proxy config changes

features/step_definitions/draft_environment_steps.rb, features/step_definitions/signon_steps.rb
=> Update Signon copy

features/mirror.feature, features/signon.feature
Missed in https://github.com/alphagov/smokey/pull/444.
=> Update more Signon copy

features/mirror.feature
I inadvertently updated too much in https://github.com/alphagov/smokey/pull/445.
Ran the branch here to make sure it actually works:
https://deploy.publishing.service.gov.uk/job/Smokey/9010/
=> Fix mirror smokey test

features/content_data_admin.feature, features/step_definitions/smokey_steps.rb, features/transition.feature
Trello: https://trello.com/c/IDm7nzwL/728-5-add-end-to-end-integration-tests
=> Add tests for content data admin

README.md, features/step_definitions/smokey_steps.rb, features/support/env.rb, features/support/http_requests.rb
This reverts commit 8c3dfeccbd2e08a7a5fe2a26d14b20343f3bbab5.
OK, yeah never mind - I think my little test yesterday was a false positive :-(.
=> Revert "Switch integration/staging to use the CDN"

features/frontend.feature
This title doesn't have an s suffix
=> Off by one error

features/ab_testing.feature
A/B testing now also works in staging and integration.
=> Run A/B test tests everywhere

features/data_gov_uk.feature
Use the canonical URL for DGU and also check the CKAN login page to make sure it’s up.
=> Check DGU and CKAN

features/email_sign_up.feature
https://github.com/alphagov/finder-frontend/pull/881
https://trello.com/c/IwDgxgTH/915-fix-smokey-tests
=> Fix use of email signup component

README.md, Rakefile, config/cucumber.yml, features/benchmarking.feature, features/data_gov_uk.feature, features/licensing.feature, features/performance_platform.feature, features/search.feature, features/support/env.rb
Add support for the new Training environment so the
Smoke Tests will work correctly in Training.
=> Add Training Environment to Smokey

features/finder_frontend.feature
Merge after https://github.com/alphagov/finder-frontend/pull/1214
https://trello.com/c/bzD1tqoa/764-remove-code-for-topic-page-finders-from-finder-frontend-m
=> [do not merge] Remove AdvancedSearch check

nagios_check_cache.py
Currently we're sending an OK but this can hide potential problems.
[Trello Card](https://trello.com/c/jpFVXZth/1146-make-icinga-generate-unknown-result-on-missing-feature-file)
=> Send an UNKNOWN alert when a feature doesn't exist

features/email_sign_up.feature
These smoke tests were failing - this fixes them!
=> Fix email signup smoke tests

features/email_sign_up.feature
The selected option wasn't being recognised.
=> Fix research and stats email tests

features/step_definitions/smartanswers_steps.rb
This was changed in https://github.com/alphagov/smart-answers/pull/4132.
=> Fix error message selector

features/finder_frontend.feature
As we're running an A/B test at the moment
=> Temporarily remove a keyword facet test step

features/search.feature, features/step_definitions/search_steps.rb
See this card for more details! https://trello.com/c/AcsleZUW/1230-revert-showing-of-facets-on-desktop
Adding a test back in that was removed in this PR https://github.com/alphagov/smokey/pull/625
=> add a test for search options

features/step_definitions/brexit_check_steps.rb
Due to https://github.com/alphagov/finder-frontend/pull/1766
=> Fix clicking incorrect Brexit checker button

features/step_definitions/brexit_check_steps.rb
Due to https://github.com/alphagov/finder-frontend/pull/1776
=> Fix another broken Brexit checker step

features/search.feature
This filter has been temporarily removed to reduce page weight.
=> Mark search org filtering test as pending

features/email_sign_up.feature
We have made changes to the [email signup flow](https://github.com/alphagov/email-alert-frontend/pull/722) and the [content on those pages](https://github.com/alphagov/email-alert-frontend/pull/732).
=> Correct Smokey tests to match new signup flow

features/email_sign_up.feature
=> Update email signup again

features/support/env.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This sets the basic authentication at the point of making any HTTP
request rather than just at the opening URL. This is being put in to
resolve a problem where we integration is failing on a test to view a
CSV preview because it lacks the basic auth needed to access the assets.
This is because we're in an odd situation where the page is hosted on
the assets hostname and the assets are hosted on the www one.
Example of this passing in integration: https://deploy.integration.publishing.service.gov.uk/job/Smokey/20074/console
=> Set basic authentication at proxy level

features/publishing_api.feature, features/publishing_tools.feature
Please see the commits for more details.
=> Add and tag features for the Publishing API

features/step_definitions/brexit_check_steps.rb
https://trello.com/c/qdieIfVv/230-batch-update-add-new-actions-and-update-existing-actions
https://trello.com/c/0S6ccXcu/231-checker-action-criteria-updates
=> Updating Brexit Check Steps to match new content in the checker

features/content_data_admin.feature
content data admin has been moved to AWS
=> enable content data admin checks in AWS only

features/publishing_api.feature
=> Fix non-matching step for Publishing API

features/publishing_tools.feature
This follows the convention of doing a "can we login"
test for other publishing apps.
=> Add Content Publisher to publishing tools feature

docs/writing-tests.md
Related to: https://github.com/alphagov/smokey/pull/681#discussion_r444320128
This PR does two things:
- Rewrite doc about Smokey and Icinga
- Document convention for "@app-" tags
Please see the commits for more details.
=> Rewrite and extend docs for adding/changing tests

features/smartanswers.feature
Although we have alerting on healthchecks, having a Smokey test for
it provides a baseline check to support Continuous Deployment [1].
[1]: https://github.com/alphagov/smokey/pull/681/commits/85d659faa30a365934691accf9339e5a42980ea5
=> Add healthcheck scenario for Smart Answers

nagios_check_cache.py
Related to: https://github.com/alphagov/govuk-puppet/pull/10499
=> Remove support for priority in audit script

config/cucumber.yml, features/benchmarking.feature, features/data_gov_uk.feature, features/licensing.feature, features/mirror.feature, features/performance_platform.feature, features/search.feature, features/support/env.rb
=> Remove training

features/brexit_check.feature, features/collections.feature, features/draft_environment.feature, features/email_sign_up.feature, features/finder_frontend.feature, features/government_frontend.feature, features/publishing_tools.feature, features/search.feature, features/travel_advice_publisher.feature
https://trello.com/c/vFPSSGb7/175-activate-continuous-deployment-for-5-more-apps
Please see this commits for more details.
- …
=> Tag scenarios for Continuous Deployment apps

features/collections.feature, features/publisher.feature
https://trello.com/c/vFPSSGb7/175-activate-continuous-deployment-for-5-more-apps
Depends on: https://github.com/alphagov/govuk-puppet/pull/10592
Previously we kept this scenario for Collections and removed it for
Publisher [1], whereas in fact we should have done the opposite.
[1]: d90d927
- Run a new build of the Smokey project and check the …
=> Fix /healthcheck scenario for collections

features/publisher.feature
https://trello.com/c/vFPSSGb7/175-activate-continuous-deployment-for-5-more-apps
> The …
=> Add missing tag for publisher feature

features/step_definitions/datagovuk_steps.rb
> The manual [Smokey job][] will pick up changes on `master` automatically. You only …
=> The class has changed

features/data_gov_uk.feature
Disable CKAN in staging tests whilst we are doing the upgrade as the site won't be available.
https://trello.com/c/ssYoWQnK/254-considerations-for-28-deployment-to-staging
- Run the [Smokey deploy …
=> Don't run tests for CKAN on Staging during upgrade

features/finder_frontend.feature
This PR specifies via the `@aws` tag to run the `@app-finder-frontend` tests against AWS, as that is where the app is served from. The reason for this is to fix the Smokey test for the finder-frontend healthcheck which is currently resolving against what would have been the public endpoint on Carrenza and which now no longer exists. This test has been consistently failing since it was introduced, and was not marked to test against AWS when other apps hosted on AWS were (see https://github.com/alphagov/smokey/commit/91a5ce94b7b96d09f5db87e63fbc3e400788de00).
are run in. You should manually test in …
=> Specify finder-frontend tests to run against AWS

features/data_gov_uk.feature
Stop tests for CKAN in production as we are doing upgrade work
> The manual [Smokey …
=> Stop tests for CKAN in prod during upgrade

features/data_gov_uk.feature
Now that the upgrade has completed, allow the smokey tests to run
> The manual [Smokey …
=> Allow CKAN tests to run

features/assets.feature
It looks like the content types for open documents has changed:
http://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html
Fixes failing test that uses an older content-type:
```
Then I should get a "Content-Type" header of "application/vnd.openxmlformats-officedocument.wordprocessingml.document" # features/step_definitions/smokey_steps.rb:191
expected: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
got: "application/vnd.oasis.opendocument.text"
(compared using ==)
(RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/smokey_steps.rb:195:in `/^I should get a "(.*)" header of "(.*)"$/'
features/assets.feature:25:in `Then I should get a "Content-Type" header of "application/vnd.openxmlformats-officedocument.wordprocessingml.docum …
```
=> Update docx content-type in failing assets test

features/brexit_check.feature, features/step_definitions/brexit_check_steps.rb
- Staging: https://deploy.blue.staging.govuk.digital/job/Smokey/7162/console
- Integration: https://deploy.integration.publishing.service.gov.uk/job/Smokey/23914/console
=> Fix brexit checker email signup test when accounts are enabled

features/step_definitions/brexit_check_steps.rb
See https://github.com/alphagov/finder-frontend/commit/6499e2b77c604107b872c461aad607a4eea56ba4#diff-79d7537dc0910cd4e8e2dfba64f9f13b3d2d1aed7da8ff36fcdf7d78ec19a043R29
=> Tweak content for accounts

features/draft_environment.feature, features/info_frontend.feature, features/manuals_frontend.feature
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This is part of enabling automatic deployments for these apps.
- Run the [Smokey deploy job][] to deploy the …
=> Tag features for info-frontend / manuals-frontend

features/support/env.rb
We no longer provision a system "chromedriver" on our machines [1].
[1]: https://github.com/alphagov/govuk-puppet/pull/10841
- …
=> Always use webdrivers to manage "chromedriver"

features/collections.feature, features/finder_frontend.feature, features/foreign_travel_advice.feature
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
Relates to: https://github.com/alphagov/email-alert-frontend/pull/916
- Run the [Smokey deploy job][] to deploy …
=> Update tests to match new email signup content

features/collections.feature, features/finder_frontend.feature, features/foreign_travel_advice.feature
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
This also removes some of the steps that were checking the page
titles, which doesn't seem to be critical to GOV.UK.
Steps to deploy a …
=> Update signup specs to match new button labels

features/finder_frontend.feature
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
This was missed in 34af49e.
- Repeat …
=> Fix incorrect button label for Finder subscription

features/collections.feature
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
These also got missed in 34af49e.
- …
=> Fix incorrect expectations for collections signup

features/content_publisher.feature, features/publishing_tools.feature
https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps
This also adds a healthcheck scenario as part of the safety checks
for enabling Continuous Deployment. Having scenarios for the same
app split across features is already a pattern for other publishing
apps, and seems a reasonable compromise, since we aim to remove them
soon [1], and clarify what this repo should look like [2].
[1]: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md#healthy-deployments
[2]: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md#explainable-smoke-tests
the behaviour of the tests changes …
=> Tag features for Content Publisher

features/coronavirus_local_restrictions.feature, features/step_definitions/coronavirus_local_restrictions_steps.rb
The coronavirus local restrictions is live again so we need to update the smokey tests
Reverts changes made here: https://github.com/alphagov/smokey/commit/e44b4e748cc5f262fdec15d82b64346db41ea0d5#diff-e34db6247bb0966fbae62429a71feadd35a34e9fcedc9877d35a097e20b57d5c
https://deploy.integration.publishing.service.gov.uk/job/Smokey/24880/console
An unrelated test is failing, but this is being fixed in another PR.
- Click "Configure" for the …
=> Update Covid postcode checker test

features/bouncer.feature
This depends on https://github.com/alphagov/bouncer/pull/278
and would allow us to enable CD for this repo.
Trello: https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps …
=> Add healthcheck scenario for bouncer

features/step_definitions/brexit_check_steps.rb
> The manual [Smokey job][] will pick up changes on `master` automatically. You only …
=> Update test following link text changes

features/manuals_publisher.feature
Dependent on https://github.com/alphagov/manuals-publisher/pull/1689
> The manual …
=> Add Manuals Publisher healthcheck test

features/content_data_admin.feature
This is for additional coverage in advance of enabling CD, see [the RFC](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md#safety-checks).
- Run the [Smokey deploy …
=> Add a test for content-data-admin's healthcheck endpoint

features/hmrc_manuals_api.feature
This is a pre-requisite to enabling CD.
> The manual [Smokey job][] will pick up changes …
=> Add Smokey test for HMRC Manuals API

features/service_manual_publisher.feature
> The manual [Smokey job][] will pick up changes on `master` automatically. You only …
=> Add Service Manual Publisher test

features/short_url_manager.feature
This is part of the work to enable continuous deployment.
Here is the run(with one other unrelated failure): https://deploy.integration.publishing.service.gov.uk/job/Smokey/25187/console 
Co-authored-by: Edward Kerry <edward.kerry@digital.cabinet-office.gov.uk>
**You need to …
=> Add a healthcheck for short url manager

features/publishing_tools.feature
These apps have recently had CD enabled on them and these features were missed.
Related PRs: #756 #761 #760
=> Tag log in features to various apps

features/email_alert_frontend.feature
Adds a smokey test for the [updated healthcheck] in Email Alert
Frontend. This is one of the steps which will allow us to enable CD for
the app.
[updated healthcheck]: https://github.com/alphagov/email-alert-frontend/pull/936 …
=> Add Email Alert Frontend smokey test

features/collections_publisher.feature, features/publishing_tools.feature
We've now added a healthcheck endpoint (https://github.com/alphagov/collections-publisher/pull/1199) and ensured that Smokey can access it (https://github.com/alphagov/collections-publisher/pull/1203). …
=> Add Smokey test for Collections Publisher

features/step_definitions/brexit_check_steps.rb
This text was updated in https://github.com/alphagov/collections/pull/2182
Succesful run: https://deploy.integration.publishing.service.gov.uk/job/Smokey/25620/
=> Update Brexit checker start text

features/step_definitions/brexit_check_steps.rb
https://trello.com/c/bjzHMu5x/736-update-checker-results-heading-3
Related to: https://github.com/alphagov/finder-frontend/pull/2367
- Run the [Smokey deploy job][] to deploy the [continuous Smokey …
=> Match new title for Brexit checker results

features/smartanswers.feature
The question structure is different as of https://github.com/alphagov/smart-answers/pull/5066.
This fixes Smokey - see https://deploy.integration.publishing.service.gov.uk/job/Smokey/25735/console
- …
=> Update Smart Answer URLs

features/collections.feature
Dependent on:
Trello:
https://trello.com/c/ssSnzp2L/640-remove-alert-from-all-the-sign-up-links
- Repeat this in Staging and …
=> Update smokey to conform with link changes

features/coronavirus_local_restrictions.feature, features/step_definitions/coronavirus_local_restrictions_steps.rb
Trello: https://trello.com/c/rPpgmgz9
The postcode checker test passes (though another unrelated test is still failing):
https://deploy.integration.publishing.service.gov.uk/job/Smokey/25793/console
- …
=> Change postcode checker test to check for redirect

features/collections.feature
The link text was changed [here](https://github.com/alphagov/collections/pull/2254).
> …
=> Fix smokey test

features/step_definitions/brexit_check_steps.rb
This text changed in a [recent Brexit checker bulk update](https://github.com/alphagov/finder-frontend/pull/2411/files)
- Repeat …
=> Update Brexit checker smokey test

features/foreign_travel_advice.feature
https://www.pivotaltracker.com/story/show/176908254
This is being reverted at the request of FCDO [1].
[1]: https://govuk.zendesk.com/agent/tickets/4417745
- Run the [Smokey deploy job][] to deploy the …
=> Restore original wording for travel advice emails

features/foreign_travel_advice.feature
The original PR was raised against master where as smokey runs against main.
> The …
=> Merge master change into main

features/frontend.feature
Depends on https://github.com/alphagov/frontend/pull/2641 being merged first.
This is to enable Continuous Deployment on Frontend.
Trello: https://trello.com/c/Pvoq4sQY/2370-5-enable-continuous-deployment-for-frontend
---
- Run the [Smokey deploy job][] …
=> Add Healthcheck tests for Frontend

features/service_manual_frontend.feature
Prep work for enabling continuous deployment.
Test Smokey run - https://deploy.integration.publishing.service.gov.uk/job/Smokey/27385/console.
Trello:
https://trello.com/c/zu7IYR6C/2385-enable-continuous-deployment-for-service-manual-frontend
**You need to manually deploy your PR …
=> Add healthcheck for Service Manual Frontend

features/info_frontend.feature
> The manual [Smokey job][] will pick up changes on `master` automatically. You only …
=> Refactor info frontend tests

features/support.feature
https://trello.com/c/YPh5Epuc/2433-5-enable-continuous-deployment-for-support-app
=> Add healthcheck for support app

features/sidekiq_monitoring.feature
Required for enabling CD.
Dependant on:
Trello:
https://trello.com/c/C1cWKFAb/2392-5-enable-continuous-deployment-for-sidekiq-monitoring
- Run the [Smokey deploy job][] to deploy the [continuous Smokey …
=> Add Sidekiq Monitoring test

features/step_definitions/coronavirus_local_restrictions_steps.rb
> The manual [Smokey job][] will pick up changes on `main` automatically. You only need …
=> Update coronavirus redirect link

features/release.feature
[Successful test run in integration](https://deploy.integration.publishing.service.gov.uk/job/Smokey/28556/console).
=> Add healthcheck for release app

features/maslow.feature
Successful run: https://deploy.blue.staging.govuk.digital/job/Smokey/10629/console
=> Add a healthcheck for maslow

features/authenticating_proxy.feature
[Successful run on integration](https://deploy.integration.publishing.service.gov.uk/job/Smokey/29254/console)
=> Fix healthcheck endpoint

features/feedback.feature
These apps have now had their errors fixed so we can begin monitoring
them for any future regressions.
Example run of this: https://deploy.integration.publishing.service.gov.uk/job/Smokey/31549/
=> Turn on feedback tests for Collections, Frontend and Smart Answers

features/data_gov_uk.feature
Re-enable check on CKAN for production
https://trello.com/c/7HPu6jyN/2647-deployment-of-ckan-29-steps
- Repeat this in Staging …
=> Update smokey to check CKAN on production

features/caching.feature, features/draft_environment.feature, features/service_manual.feature, features/signon.feature
Tested in integration: https://deploy.integration.publishing.service.gov.uk/job/Smokey/38703/console
Needs manual deployment to update smokey-loop (though it's really a no-op in this case).
[Smokey deploy job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey_Deploy/
[Trello](https://trello.com/c/9BPpFRBe/851)
=> Enable some more tests against the Replatforming EKS cluster.

features/service_manual.feature
Needed for individual testing for service-manual-frontend in the
EKS platform.
> The …
=> Add tag for service-manual-frontend

features/step_definitions/feedback_steps.rb
We're removing jQuery and this code is now causing a test to fail. Removing jQuery will fix it.
=> Quick fix to remove jQuery expectation

config/cucumber.yml, features/support/env.rb
This reverts commit 6a44753a56ae9ad906e5ac2afd8a2cac1c7d9c76.
This was added for a test replatforming environment that no longer
exists.
- …
=> Revert "Add test environment"

features/benchmarking.feature, features/caching.feature, features/contacts.feature, features/content_data_admin.feature, features/finder_frontend.feature, features/frontend.feature, features/government_frontend.feature, features/mirror.feature, features/publishing_tools.feature, features/router.feature, features/smartanswers.feature, features/waf.feature, features/whitehall.feature
This was missed in [^1].
[^1]: https://github.com/alphagov/smokey/pull/779/files
- Run the [Smokey deploy job][] to deploy the [continuous …
=> Remove redundant "@aws" tags

docs/writing-tests.md
I've also done some minor rewrites of the overall guidance to make
it clearer when read in isolation.
None of the original meaning should have changed so the easiest way
to review would just be to read the rendered version.
👉 [Rendered version](https://github.com/alphagov/smokey/blob/document-tags/docs/writing-tests.md)
=> Add documentation about @... tags in use

Dockerfile, config/cucumber.yml, features/benchmarking.feature, jenkins.sh
This stops the scenarios in benchmarking.feature from running when
we do a full run of Smokey. However, the tests are still run by the
Smokey Loop. Since we're removing the single alert associated with
a full run of Smokey [^1], the impact of these tests failing is low
and we may as well just run them.
Long term we should reconsider the need for these specific tests:
it's unclear why most of them exist.
In practice I don't think the failures will cause a problem for full runs 
of Smokey in Integration or Staging, compared to other failures:
[^1]: https://github.com/alphagov/govuk-puppet/pull/11610
the …
=> Remove unnecessary @benchmarking tag

tests_json_output.sh
This isn't used anywhere and wasn't documented.
Tested with the Smokey Loop and works on Integration ✅.
=> Remove redundant "disabled_in_icinga" tag

features/support/env.rb
https://trello.com/c/DL5omRGP/230-smokey-needs-java-and-a-glitchy-proxy-server-to-run-tests
None of these have an impact on the tests we run today.
Tested and works in Integration Jenkins ✅.
Might be worth doing a test run of this in Production as well, 
just in case there are any differences.
=> Remove cross-site request and JS log filters

README.md
> The manual [Smokey job][] will pick up changes on `main` automatically. You only need …
=> Fix missing single quote in command

features/support/hooks.rb
=> Change puts to log to fix cucumber deprecation

features/support/env.rb, features/support/hooks.rb
These were missed following a rebase of [^1].
[^1]: https://github.com/alphagov/smokey/pull/931
Tested and works on Integration ✅. We're just getting the usual / recent email and A/B failures.
=> Fix bugs in new Sentry monitoring hook

features/support/hooks.rb
This is a particular problem for feedback.feature e.g.
Check "is this page useful?" email survey
Tested locally and drilldown now works as expected.
=> Fix drilldown for scenarios with quotes

features/support/hooks.rb
https://github.com/alphagov/smokey/pull/946
This was partly another relic from a previous rebase [^1], but also
a more fundamental issues with the approach I had used to test async
errors, which I have since corrected [^2].
[^1]: https://github.com/alphagov/smokey/pull/931
[^2]: https://github.com/alphagov/smokey/pull/933#pullrequestreview-969638404
Tested locally and issues are now being created as expected.
=> Fix Sentry reporting for async JS issues

features/support/hooks.rb
When a request to visit a page fails we get:
- A normal scenario failure, which was picked up by the shorter
"After" block. This reports an issue to Sentry as expected.
- A "SEVERE" browser log for the failed request, which was picked
up by the long, async "After" block. This leads to another issue.
The "async" block is the one that needs fixing: it should only be
picking up on "out-of-band" JS errors; that is, when we visit a
page and see some red in the console, despite the general content
on the page being sufficient for the scenario to pass.
Having two "After" blocks was making it hard to explain the control
flow, so as well as fixing the problem I've also combined them into
one as they both perform similar error reporting …
=> Fix duplicate Sentry issues for request errors

Gemfile, Gemfile.lock, README.md, features/support/env.rb
=> Add rate limit token support through chrome devtools

features/support/browser.rb, features/support/hooks.rb
This fixes two bugs:
- One where error logs were leaking into other scenarios and
causing them to fail.
- One where our own code failed trying to analyse logs that
weren't valid JSON.
Please see the commits for more details.
Tested with [a full run on Integration](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40083/console) ✅.
=> Fix two bugs causing incorrect test failures

features/publishing_tools.feature
The content on this application has changed and is causing tests to fail. This change updates the test to match the application.
=> Change `Sign out` to `Log out`

features/ab_testing.feature, features/step_definitions/ab_testing_steps.rb
This was easier to fix than justify its removal. I've
also done a bit of tidying up of its related steps.
Tested and works on [Integration Jenkins](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40326/console) ✅.
=> Fix broken / disabled AB Test scenario

features/caching.feature, features/collections.feature, features/draft_environment.feature, features/finder_frontend.feature, features/frontend.feature, features/gov_uk.feature, features/government_frontend.feature, features/info_frontend.feature, features/transition.feature
This PR contains some small, hopefully non-controversial
changes to some scenarios that I noticed in my audit and
general work on this repo.
Please see the commits for more details.
Tested and works on [Integration Jenkins](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40508/console) ✅*.
*The failures are all JS-related and unchanged from `main`.
=> Small improvements to individual scenarios

Jenkinsfile
https://trello.com/c/JcY1L7so/2942-automatically-run-smokeydeploy-when-a-smokey-change-is-merged-3
=> Add repoName to Jenkinsfile

features/apps/frontend.feature
Update scenario name to fix old reference to mapit.
https://trello.com/c/LMRiT7yz/1581-retire-mapit-and-mapit-scripts
=> Frontend no longer uses Mapit for local_transactions

features/apps/transition.feature
This allows us to run the specific tests as part of the Continuous Deployment pipeline.
[Trello card](https://trello.com/c/VgRHbI98)
=> Tag Transition tests

features/apps/government_frontend.feature, features/apps/service_manual_frontend.feature
We're retiring the app, however the test itself was simple and has some merit in being moved to Government Frontend's own smokey tests.
=> Remove Service Manual Frontend

features/apps/frontend.feature
=> Skips licence smoke tests in integration

features/apps/manuals_publisher.feature
Fix failing test: change text to seek on Manuals Publisher your manuals landing page to match changes to interface resulting from moving app to the new govuk design system.
=> Update Manuals Publisher feature test

Gemfile.lock
=> Revert "Bump selenium-webdriver from 4.15.0 to 4.16.0"

docs/deployment.md, features/step_definitions/ab_testing_steps.rb, features/step_definitions/smokey_steps.rb
See commits for details.
Manually tested branch as per deployment instructions (which I've added a tweak to here).
=> Some small tweaks

docs/deployment.md, features/apps/finder_frontend.feature, features/apps/frontend.feature, features/apps/smartanswers.feature, features/apps/smokey.feature, features/data_gov_uk.feature, features/origin.feature, features/step_definitions/smartanswers_steps.rb, features/step_definitions/smokey_steps.rb
Some small improvements to make the test suite more cohesive.
Tested on Integration: https://argo.eks.integration.govuk.digital/applications/cluster-services/smokey?orphaned=false&operation=false&resource=&node=batch%2FJob%2Fapps%2Fsmokey-202401171409&tab=logs
=> Refactor Smokey tests

README.md
This should have been done in #1238.
=> Add missing \ character

features/cdn.feature
Updated the postcode to our current office, previous postcode didn't return any results.
=> Fix postcode used to test POST request for CDN

features/apps/imminence.feature
- Checking for the name isn't really adding anything, and it will cause problems when we're doing the renaming.
https://trello.com/c/HAEH2bVF/2338-rename-imminence
(Passing in integration)
=> Remove check for Imminence's name ahead of imminence renaming

features/step_definitions/smokey_steps.rb
Confirmed working in integration: https://argo.eks.integration.govuk.digital/applications/cluster-services/smokey?orphaned=false&resource=&node=batch%2FJob%2Fapps%2Fsmokey-28563230%2F0
=> Add special case for imminence landing page
